ainfo_TD[0] = TextDrawCreate(282.2002, 7.6577, "LD_SPAC:white"); // пусто
TextDrawTextSize(ainfo_TD[0], 32.0000, 14.0000);
TextDrawAlignment(ainfo_TD[0], 1);
TextDrawColor(ainfo_TD[0], 252645375);
TextDrawBackgroundColor(ainfo_TD[0], 255);
TextDrawFont(ainfo_TD[0], 4);
TextDrawSetProportional(ainfo_TD[0], 0);
TextDrawSetShadow(ainfo_TD[0], 0);

ainfo_TD[1] = TextDrawCreate(305.9002, 4.2643, "LD_BEAT:chit"); // пусто
TextDrawTextSize(ainfo_TD[1], 18.0000, 21.0000);
TextDrawAlignment(ainfo_TD[1], 1);
TextDrawColor(ainfo_TD[1], 252645375);
TextDrawBackgroundColor(ainfo_TD[1], 255);
TextDrawFont(ainfo_TD[1], 4);
TextDrawSetProportional(ainfo_TD[1], 0);
TextDrawSetShadow(ainfo_TD[1], 0);

ainfo_TD[2] = TextDrawCreate(271.9002, 1.4821, "LD_BEAT:chit"); // пусто
TextDrawTextSize(ainfo_TD[2], 22.0000, 26.0000);
TextDrawAlignment(ainfo_TD[2], 1);
TextDrawColor(ainfo_TD[2], 865730559);
TextDrawBackgroundColor(ainfo_TD[2], 255);
TextDrawFont(ainfo_TD[2], 4);
TextDrawSetProportional(ainfo_TD[2], 0);
TextDrawSetShadow(ainfo_TD[2], 0);

ainfo_TD[3] = TextDrawCreate(282.8002, 8.4133, "5"); // пусто
TextDrawLetterSize(ainfo_TD[3], 0.2531, 1.2117);
TextDrawAlignment(ainfo_TD[3], 2);
TextDrawColor(ainfo_TD[3], -1);
TextDrawBackgroundColor(ainfo_TD[3], 255);
TextDrawFont(ainfo_TD[3], 3);
TextDrawSetProportional(ainfo_TD[3], 1);
TextDrawSetShadow(ainfo_TD[3], 0);

ainfo_TD[4] = TextDrawCreate(304.4002, 9.6043, "REPORTS"); // пусто
TextDrawLetterSize(ainfo_TD[4], 0.1263, 1.0126);
TextDrawAlignment(ainfo_TD[4], 2);
TextDrawColor(ainfo_TD[4], -1);
TextDrawBackgroundColor(ainfo_TD[4], 255);
TextDrawFont(ainfo_TD[4], 2);
TextDrawSetProportional(ainfo_TD[4], 1);
TextDrawSetShadow(ainfo_TD[4], 0);

ainfo_TD[5] = TextDrawCreate(327.1013, 7.8533, "LD_SPAC:white"); // пусто
TextDrawTextSize(ainfo_TD[5], 32.0000, 14.0000);
TextDrawAlignment(ainfo_TD[5], 1);
TextDrawColor(ainfo_TD[5], 252645375);
TextDrawBackgroundColor(ainfo_TD[5], 255);
TextDrawFont(ainfo_TD[5], 4);
TextDrawSetProportional(ainfo_TD[5], 0);
TextDrawSetShadow(ainfo_TD[5], 0);

ainfo_TD[6] = TextDrawCreate(351.2003, 4.1665, "LD_BEAT:chit"); // пусто
TextDrawTextSize(ainfo_TD[6], 18.0000, 21.0000);
TextDrawAlignment(ainfo_TD[6], 1);
TextDrawColor(ainfo_TD[6], 252645375);
TextDrawBackgroundColor(ainfo_TD[6], 255);
TextDrawFont(ainfo_TD[6], 4);
TextDrawSetProportional(ainfo_TD[6], 0);
TextDrawSetShadow(ainfo_TD[6], 0);

ainfo_TD[7] = TextDrawCreate(320.0003, 1.6821, "LD_BEAT:chit"); // пусто
TextDrawTextSize(ainfo_TD[7], 22.0000, 26.0000);
TextDrawAlignment(ainfo_TD[7], 1);
TextDrawColor(ainfo_TD[7], 865730559);
TextDrawBackgroundColor(ainfo_TD[7], 255);
TextDrawFont(ainfo_TD[7], 4);
TextDrawSetProportional(ainfo_TD[7], 0);
TextDrawSetShadow(ainfo_TD[7], 0);

ainfo_TD[8] = TextDrawCreate(330.9004, 8.9111, "7"); // пусто
TextDrawLetterSize(ainfo_TD[8], 0.2531, 1.2117);
TextDrawAlignment(ainfo_TD[8], 2);
TextDrawColor(ainfo_TD[8], -1);
TextDrawBackgroundColor(ainfo_TD[8], 255);
TextDrawFont(ainfo_TD[8], 3);
TextDrawSetProportional(ainfo_TD[8], 1);
TextDrawSetShadow(ainfo_TD[8], 0);

ainfo_TD[9] = TextDrawCreate(349.4001, 9.6043, "admins"); // пусто
TextDrawLetterSize(ainfo_TD[9], 0.1263, 1.0126);
TextDrawAlignment(ainfo_TD[9], 2);
TextDrawColor(ainfo_TD[9], -1);
TextDrawBackgroundColor(ainfo_TD[9], 255);
TextDrawFont(ainfo_TD[9], 2);
TextDrawSetProportional(ainfo_TD[9], 1);
TextDrawSetShadow(ainfo_TD[9], 0);