AutoSalon_TD[0] = TextDrawCreate(482.6329, 135.0879, "ld_beat:chit"); // header box
TextDrawTextSize(AutoSalon_TD[0], 15.0000, 15.0000);
TextDrawAlignment(AutoSalon_TD[0], 1);
TextDrawColor(AutoSalon_TD[0], 1112566783);
TextDrawBackgroundColor(AutoSalon_TD[0], 255);
TextDrawFont(AutoSalon_TD[0], 4);
TextDrawSetProportional(AutoSalon_TD[0], 0);
TextDrawSetShadow(AutoSalon_TD[0], 0);

AutoSalon_TD[1] = TextDrawCreate(591.3325, 135.1737, "ld_beat:chit"); // header box
TextDrawTextSize(AutoSalon_TD[1], 15.0000, 15.0000);
TextDrawAlignment(AutoSalon_TD[1], 1);
TextDrawColor(AutoSalon_TD[1], 1112566783);
TextDrawBackgroundColor(AutoSalon_TD[1], 255);
TextDrawFont(AutoSalon_TD[1], 4);
TextDrawSetProportional(AutoSalon_TD[1], 0);
TextDrawSetShadow(AutoSalon_TD[1], 0);

AutoSalon_TD[2] = TextDrawCreate(482.4992, 302.8869, "ld_beat:chit"); // body box
TextDrawTextSize(AutoSalon_TD[2], 15.0000, 15.0000);
TextDrawAlignment(AutoSalon_TD[2], 1);
TextDrawColor(AutoSalon_TD[2], 336860415);
TextDrawBackgroundColor(AutoSalon_TD[2], 255);
TextDrawFont(AutoSalon_TD[2], 4);
TextDrawSetProportional(AutoSalon_TD[2], 0);
TextDrawSetShadow(AutoSalon_TD[2], 0);

AutoSalon_TD[3] = TextDrawCreate(591.4992, 302.9873, "ld_beat:chit"); // body box
TextDrawTextSize(AutoSalon_TD[3], 15.0000, 15.0000);
TextDrawAlignment(AutoSalon_TD[3], 1);
TextDrawColor(AutoSalon_TD[3], 336860415);
TextDrawBackgroundColor(AutoSalon_TD[3], 255);
TextDrawFont(AutoSalon_TD[3], 4);
TextDrawSetProportional(AutoSalon_TD[3], 0);
TextDrawSetShadow(AutoSalon_TD[3], 0);

AutoSalon_TD[4] = TextDrawCreate(490.3327, 137.5767, "LD_SPAC:white"); // header box
TextDrawTextSize(AutoSalon_TD[4], 108.0000, 19.0000);
TextDrawAlignment(AutoSalon_TD[4], 1);
TextDrawColor(AutoSalon_TD[4], 1112566783);
TextDrawBackgroundColor(AutoSalon_TD[4], 255);
TextDrawFont(AutoSalon_TD[4], 4);
TextDrawSetProportional(AutoSalon_TD[4], 0);
TextDrawSetShadow(AutoSalon_TD[4], 0);

AutoSalon_TD[5] = TextDrawCreate(484.8995, 142.9696, "LD_SPAC:white"); // header box
TextDrawTextSize(AutoSalon_TD[5], 119.0000, 15.0000);
TextDrawAlignment(AutoSalon_TD[5], 1);
TextDrawColor(AutoSalon_TD[5], 1112566783);
TextDrawBackgroundColor(AutoSalon_TD[5], 255);
TextDrawFont(AutoSalon_TD[5], 4);
TextDrawSetProportional(AutoSalon_TD[5], 0);
TextDrawSetShadow(AutoSalon_TD[5], 0);

AutoSalon_TD[6] = TextDrawCreate(490.3323, 275.4989, "LD_SPAC:white"); // body box
TextDrawTextSize(AutoSalon_TD[6], 110.0000, 40.0000);
TextDrawAlignment(AutoSalon_TD[6], 1);
TextDrawColor(AutoSalon_TD[6], 336860415);
TextDrawBackgroundColor(AutoSalon_TD[6], 255);
TextDrawFont(AutoSalon_TD[6], 4);
TextDrawSetProportional(AutoSalon_TD[6], 0);
TextDrawSetShadow(AutoSalon_TD[6], 0);

AutoSalon_TD[7] = TextDrawCreate(484.9996, 157.9033, "LD_SPAC:white"); // body box
TextDrawTextSize(AutoSalon_TD[7], 119.0000, 152.0000);
TextDrawAlignment(AutoSalon_TD[7], 1);
TextDrawColor(AutoSalon_TD[7], 336860415);
TextDrawBackgroundColor(AutoSalon_TD[7], 255);
TextDrawFont(AutoSalon_TD[7], 4);
TextDrawSetProportional(AutoSalon_TD[7], 0);
TextDrawSetShadow(AutoSalon_TD[7], 0);

AutoSalon_TD[8] = TextDrawCreate(486.9992, 159.9777, "LD_SPAC:white"); // ionoi
TextDrawTextSize(AutoSalon_TD[8], 115.0000, 2.0000);
TextDrawAlignment(AutoSalon_TD[8], 1);
TextDrawColor(AutoSalon_TD[8], 606348543);
TextDrawBackgroundColor(AutoSalon_TD[8], 255);
TextDrawFont(AutoSalon_TD[8], 4);
TextDrawSetProportional(AutoSalon_TD[8], 0);
TextDrawSetShadow(AutoSalon_TD[8], 0);

AutoSalon_TD[9] = TextDrawCreate(544.3322, 141.0507, "AUTOSALON"); // header tx
TextDrawLetterSize(AutoSalon_TD[9], 0.1972, 0.9236);
TextDrawAlignment(AutoSalon_TD[9], 2);
TextDrawColor(AutoSalon_TD[9], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[9], 255);
TextDrawFont(AutoSalon_TD[9], 1);
TextDrawSetProportional(AutoSalon_TD[9], 1);
TextDrawSetShadow(AutoSalon_TD[9], 0);

AutoSalon_TD[10] = TextDrawCreate(544.3328, 147.6876, ""); // header tx Car Class
TextDrawLetterSize(AutoSalon_TD[10], 0.1419, 0.6915);
TextDrawAlignment(AutoSalon_TD[10], 2);
TextDrawColor(AutoSalon_TD[10], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[10], 255);
TextDrawFont(AutoSalon_TD[10], 1);
TextDrawSetProportional(AutoSalon_TD[10], 1);
TextDrawSetShadow(AutoSalon_TD[10], 0);

AutoSalon_TD[11] = TextDrawCreate(585.5321, 173.6654, "LD_SPAC:white"); // range 1 bt ">>"
TextDrawTextSize(AutoSalon_TD[11], 15.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[11], 1);
TextDrawColor(AutoSalon_TD[11], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[11], 255);
TextDrawFont(AutoSalon_TD[11], 4);
TextDrawSetProportional(AutoSalon_TD[11], 0);
TextDrawSetShadow(AutoSalon_TD[11], 0);

AutoSalon_TD[12] = TextDrawCreate(488.1989, 173.6654, "LD_SPAC:white"); // range 1 bt "<<"
TextDrawTextSize(AutoSalon_TD[12], 15.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[12], 1);
TextDrawColor(AutoSalon_TD[12], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[12], 255);
TextDrawFont(AutoSalon_TD[12], 4);
TextDrawSetProportional(AutoSalon_TD[12], 0);
TextDrawSetShadow(AutoSalon_TD[12], 0);

AutoSalon_TD[13] = TextDrawCreate(504.1990, 173.6654, "LD_SPAC:white"); // range 1 bt "car model"
TextDrawTextSize(AutoSalon_TD[13], 80.3498, 14.0000);
TextDrawAlignment(AutoSalon_TD[13], 1);
TextDrawColor(AutoSalon_TD[13], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[13], 255);
TextDrawFont(AutoSalon_TD[13], 4);
TextDrawSetProportional(AutoSalon_TD[13], 0);
TextDrawSetShadow(AutoSalon_TD[13], 0);

AutoSalon_TD[14] = TextDrawCreate(495.5320, 176.7247, "<<"); // range 1 tx "<<"
TextDrawLetterSize(AutoSalon_TD[14], 0.1972, 0.9236);
TextDrawTextSize(AutoSalon_TD[14], 15.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[14], 2);
TextDrawColor(AutoSalon_TD[14], -1768515841);
TextDrawUseBox(AutoSalon_TD[14], 1);
TextDrawBoxColor(AutoSalon_TD[14], 0);
TextDrawBackgroundColor(AutoSalon_TD[14], 255);
TextDrawFont(AutoSalon_TD[14], 1);
TextDrawSetProportional(AutoSalon_TD[14], 1);
TextDrawSetShadow(AutoSalon_TD[14], 0);
TextDrawSetSelectable(AutoSalon_TD[14], true);

AutoSalon_TD[15] = TextDrawCreate(592.8648, 176.7247, ">>"); // range 1 tx ">>"
TextDrawLetterSize(AutoSalon_TD[15], 0.1972, 0.9236);
TextDrawTextSize(AutoSalon_TD[15], 15.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[15], 2);
TextDrawColor(AutoSalon_TD[15], -1768515841);
TextDrawUseBox(AutoSalon_TD[15], 1);
TextDrawBoxColor(AutoSalon_TD[15], 0);
TextDrawBackgroundColor(AutoSalon_TD[15], 255);
TextDrawFont(AutoSalon_TD[15], 1);
TextDrawSetProportional(AutoSalon_TD[15], 1);
TextDrawSetShadow(AutoSalon_TD[15], 0);
TextDrawSetSelectable(AutoSalon_TD[15], true);

AutoSalon_TD[16] = TextDrawCreate(544.1994, 165.5247, "CHOSE MODEL"); // range 1 tx "chs model"
TextDrawLetterSize(AutoSalon_TD[16], 0.1419, 0.6915);
TextDrawAlignment(AutoSalon_TD[16], 2);
TextDrawColor(AutoSalon_TD[16], 1112566783);
TextDrawBackgroundColor(AutoSalon_TD[16], 255);
TextDrawFont(AutoSalon_TD[16], 1);
TextDrawSetProportional(AutoSalon_TD[16], 1);
TextDrawSetShadow(AutoSalon_TD[16], 0);

AutoSalon_TD[17] = TextDrawCreate(585.5322, 198.9687, "LD_SPAC:white"); // range 2 bt ">>"
TextDrawTextSize(AutoSalon_TD[17], 15.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[17], 1);
TextDrawColor(AutoSalon_TD[17], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[17], 255);
TextDrawFont(AutoSalon_TD[17], 4);
TextDrawSetProportional(AutoSalon_TD[17], 0);
TextDrawSetShadow(AutoSalon_TD[17], 0);

AutoSalon_TD[18] = TextDrawCreate(488.1990, 198.9687, "LD_SPAC:white"); // range 2 bt "<<"
TextDrawTextSize(AutoSalon_TD[18], 15.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[18], 1);
TextDrawColor(AutoSalon_TD[18], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[18], 255);
TextDrawFont(AutoSalon_TD[18], 4);
TextDrawSetProportional(AutoSalon_TD[18], 0);
TextDrawSetShadow(AutoSalon_TD[18], 0);

AutoSalon_TD[19] = TextDrawCreate(504.1990, 198.9687, "LD_SPAC:white"); // range 2 bt "car color"
TextDrawTextSize(AutoSalon_TD[19], 80.3498, 14.0000);
TextDrawAlignment(AutoSalon_TD[19], 1);
TextDrawColor(AutoSalon_TD[19], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[19], 255);
TextDrawFont(AutoSalon_TD[19], 4);
TextDrawSetProportional(AutoSalon_TD[19], 0);
TextDrawSetShadow(AutoSalon_TD[19], 0);

AutoSalon_TD[20] = TextDrawCreate(495.5320, 202.0281, "<<"); // range 2 tx "<<"
TextDrawLetterSize(AutoSalon_TD[20], 0.1972, 0.9236);
TextDrawTextSize(AutoSalon_TD[20], 15.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[20], 2);
TextDrawColor(AutoSalon_TD[20], -1768515841);
TextDrawUseBox(AutoSalon_TD[20], 1);
TextDrawBoxColor(AutoSalon_TD[20], 0);
TextDrawBackgroundColor(AutoSalon_TD[20], 255);
TextDrawFont(AutoSalon_TD[20], 1);
TextDrawSetProportional(AutoSalon_TD[20], 1);
TextDrawSetShadow(AutoSalon_TD[20], 0);
TextDrawSetSelectable(AutoSalon_TD[20], true);

AutoSalon_TD[21] = TextDrawCreate(592.8648, 202.0281, ">>"); // range 2 tx ">>"
TextDrawLetterSize(AutoSalon_TD[21], 0.1972, 0.9236);
TextDrawTextSize(AutoSalon_TD[21], 15.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[21], 2);
TextDrawColor(AutoSalon_TD[21], -1768515841);
TextDrawUseBox(AutoSalon_TD[21], 1);
TextDrawBoxColor(AutoSalon_TD[21], 0);
TextDrawBackgroundColor(AutoSalon_TD[21], 255);
TextDrawFont(AutoSalon_TD[21], 1);
TextDrawSetProportional(AutoSalon_TD[21], 1);
TextDrawSetShadow(AutoSalon_TD[21], 0);
TextDrawSetSelectable(AutoSalon_TD[21], true);

AutoSalon_TD[22] = TextDrawCreate(544.1994, 190.8280, "CHOSE COLOR"); // range 2 tx "chs color"
TextDrawLetterSize(AutoSalon_TD[22], 0.1419, 0.6915);
TextDrawAlignment(AutoSalon_TD[22], 2);
TextDrawColor(AutoSalon_TD[22], 1112566783);
TextDrawBackgroundColor(AutoSalon_TD[22], 255);
TextDrawFont(AutoSalon_TD[22], 1);
TextDrawSetProportional(AutoSalon_TD[22], 1);
TextDrawSetShadow(AutoSalon_TD[22], 0);

AutoSalon_TD[23] = TextDrawCreate(594.8322, 287.3240, "ld_beat:chit"); // box - characteristic
TextDrawTextSize(AutoSalon_TD[23], 7.0000, 7.0000);
TextDrawAlignment(AutoSalon_TD[23], 1);
TextDrawColor(AutoSalon_TD[23], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[23], 255);
TextDrawFont(AutoSalon_TD[23], 4);
TextDrawSetProportional(AutoSalon_TD[23], 0);
TextDrawSetShadow(AutoSalon_TD[23], 0);

AutoSalon_TD[24] = TextDrawCreate(486.4992, 287.3240, "ld_beat:chit"); // box - characteristic
TextDrawTextSize(AutoSalon_TD[24], 7.0000, 7.0000);
TextDrawAlignment(AutoSalon_TD[24], 1);
TextDrawColor(AutoSalon_TD[24], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[24], 255);
TextDrawFont(AutoSalon_TD[24], 4);
TextDrawSetProportional(AutoSalon_TD[24], 0);
TextDrawSetShadow(AutoSalon_TD[24], 0);

AutoSalon_TD[25] = TextDrawCreate(490.1990, 224.2725, "LD_SPAC:white"); // box - characteristic
TextDrawTextSize(AutoSalon_TD[25], 108.0000, 69.0000);
TextDrawAlignment(AutoSalon_TD[25], 1);
TextDrawColor(AutoSalon_TD[25], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[25], 255);
TextDrawFont(AutoSalon_TD[25], 4);
TextDrawSetProportional(AutoSalon_TD[25], 0);
TextDrawSetShadow(AutoSalon_TD[25], 0);

AutoSalon_TD[26] = TextDrawCreate(487.8658, 226.3466, "LD_SPAC:white"); // box - characteristic
TextDrawTextSize(AutoSalon_TD[26], 113.0000, 64.0000);
TextDrawAlignment(AutoSalon_TD[26], 1);
TextDrawColor(AutoSalon_TD[26], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[26], 255);
TextDrawFont(AutoSalon_TD[26], 4);
TextDrawSetProportional(AutoSalon_TD[26], 0);
TextDrawSetShadow(AutoSalon_TD[26], 0);

AutoSalon_TD[27] = TextDrawCreate(544.1994, 215.7167, "CHARACTER CAR"); // text - characteristic
TextDrawLetterSize(AutoSalon_TD[27], 0.1419, 0.6915);
TextDrawAlignment(AutoSalon_TD[27], 2);
TextDrawColor(AutoSalon_TD[27], 1112566783);
TextDrawBackgroundColor(AutoSalon_TD[27], 255);
TextDrawFont(AutoSalon_TD[27], 1);
TextDrawSetProportional(AutoSalon_TD[27], 1);
TextDrawSetShadow(AutoSalon_TD[27], 0);

AutoSalon_TD[28] = TextDrawCreate(492.4327, 235.4732, "LD_SPAC:white"); // line 1 bg - "max speed"
TextDrawTextSize(AutoSalon_TD[28], 103.0000, 4.0000);
TextDrawAlignment(AutoSalon_TD[28], 1);
TextDrawColor(AutoSalon_TD[28], 606348543);
TextDrawBackgroundColor(AutoSalon_TD[28], 255);
TextDrawFont(AutoSalon_TD[28], 4);
TextDrawSetProportional(AutoSalon_TD[28], 0);
TextDrawSetShadow(AutoSalon_TD[28], 0);

AutoSalon_TD[29] = TextDrawCreate(492.4327, 251.2357, "LD_SPAC:white"); // line 2 bg - "acceler"
TextDrawTextSize(AutoSalon_TD[29], 103.0000, 4.0000);
TextDrawAlignment(AutoSalon_TD[29], 1);
TextDrawColor(AutoSalon_TD[29], 606348543);
TextDrawBackgroundColor(AutoSalon_TD[29], 255);
TextDrawFont(AutoSalon_TD[29], 4);
TextDrawSetProportional(AutoSalon_TD[29], 0);
TextDrawSetShadow(AutoSalon_TD[29], 0);

AutoSalon_TD[30] = TextDrawCreate(492.4327, 267.4132, "LD_SPAC:white"); // line 3 bg - "braking"
TextDrawTextSize(AutoSalon_TD[30], 103.0000, 4.0000);
TextDrawAlignment(AutoSalon_TD[30], 1);
TextDrawColor(AutoSalon_TD[30], 606348543);
TextDrawBackgroundColor(AutoSalon_TD[30], 255);
TextDrawFont(AutoSalon_TD[30], 4);
TextDrawSetProportional(AutoSalon_TD[30], 0);
TextDrawSetShadow(AutoSalon_TD[30], 0);

AutoSalon_TD[31] = TextDrawCreate(492.4327, 283.5914, "LD_SPAC:white"); // line 4 bg - "clutch"
TextDrawTextSize(AutoSalon_TD[31], 103.0000, 4.0000);
TextDrawAlignment(AutoSalon_TD[31], 1);
TextDrawColor(AutoSalon_TD[31], 606348543);
TextDrawBackgroundColor(AutoSalon_TD[31], 255);
TextDrawFont(AutoSalon_TD[31], 4);
TextDrawSetProportional(AutoSalon_TD[31], 0);
TextDrawSetShadow(AutoSalon_TD[31], 0);

AutoSalon_TD[32] = TextDrawCreate(594.8327, 223.0281, "ld_beat:chit"); // box - characteristic
TextDrawTextSize(AutoSalon_TD[32], 7.0000, 7.0000);
TextDrawAlignment(AutoSalon_TD[32], 1);
TextDrawColor(AutoSalon_TD[32], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[32], 255);
TextDrawFont(AutoSalon_TD[32], 4);
TextDrawSetProportional(AutoSalon_TD[32], 0);
TextDrawSetShadow(AutoSalon_TD[32], 0);

AutoSalon_TD[33] = TextDrawCreate(486.4995, 223.0281, "ld_beat:chit"); // box - characteristic
TextDrawTextSize(AutoSalon_TD[33], 7.0000, 7.0000);
TextDrawAlignment(AutoSalon_TD[33], 1);
TextDrawColor(AutoSalon_TD[33], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[33], 255);
TextDrawFont(AutoSalon_TD[33], 4);
TextDrawSetProportional(AutoSalon_TD[33], 0);
TextDrawSetShadow(AutoSalon_TD[33], 0);

AutoSalon_TD[34] = TextDrawCreate(515.8654, 298.6799, "BUY"); // range 3 tx - "buy"
TextDrawLetterSize(AutoSalon_TD[34], 0.1972, 0.9236);
TextDrawTextSize(AutoSalon_TD[34], 56.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[34], 2);
TextDrawColor(AutoSalon_TD[34], -1768515841);
TextDrawBackgroundColor(AutoSalon_TD[34], 255);
TextDrawFont(AutoSalon_TD[34], 1);
TextDrawSetProportional(AutoSalon_TD[34], 1);
TextDrawSetShadow(AutoSalon_TD[34], 0);
TextDrawSetSelectable(AutoSalon_TD[34], true);

AutoSalon_TD[35] = TextDrawCreate(487.8658, 296.0357, "LD_SPAC:white"); // range 3 box - "buy"
TextDrawTextSize(AutoSalon_TD[35], 56.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[35], 1);
TextDrawColor(AutoSalon_TD[35], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[35], 255);
TextDrawFont(AutoSalon_TD[35], 4);
TextDrawSetProportional(AutoSalon_TD[35], 0);
TextDrawSetShadow(AutoSalon_TD[35], 0);

AutoSalon_TD[36] = TextDrawCreate(492.1989, 228.5760, "MAX SPEED"); // line 1 tx - "max speed"
TextDrawLetterSize(AutoSalon_TD[36], 0.1419, 0.6915);
TextDrawAlignment(AutoSalon_TD[36], 1);
TextDrawColor(AutoSalon_TD[36], -1768515841);
TextDrawBackgroundColor(AutoSalon_TD[36], 255);
TextDrawFont(AutoSalon_TD[36], 1);
TextDrawSetProportional(AutoSalon_TD[36], 1);
TextDrawSetShadow(AutoSalon_TD[36], 0);

AutoSalon_TD[37] = TextDrawCreate(492.1989, 244.3390, "ACCELER"); // line 2 tx - "acceler"
TextDrawLetterSize(AutoSalon_TD[37], 0.1419, 0.6915);
TextDrawAlignment(AutoSalon_TD[37], 1);
TextDrawColor(AutoSalon_TD[37], -1768515841);
TextDrawBackgroundColor(AutoSalon_TD[37], 255);
TextDrawFont(AutoSalon_TD[37], 1);
TextDrawSetProportional(AutoSalon_TD[37], 1);
TextDrawSetShadow(AutoSalon_TD[37], 0);

AutoSalon_TD[38] = TextDrawCreate(492.1989, 260.5162, "BRAKING"); // line 3 tx - "braking"
TextDrawLetterSize(AutoSalon_TD[38], 0.1419, 0.6915);
TextDrawAlignment(AutoSalon_TD[38], 1);
TextDrawColor(AutoSalon_TD[38], -1768515841);
TextDrawBackgroundColor(AutoSalon_TD[38], 255);
TextDrawFont(AutoSalon_TD[38], 1);
TextDrawSetProportional(AutoSalon_TD[38], 1);
TextDrawSetShadow(AutoSalon_TD[38], 0);

AutoSalon_TD[39] = TextDrawCreate(492.1989, 276.6943, "CLUTCH"); // line 4 tx - "clutch"
TextDrawLetterSize(AutoSalon_TD[39], 0.1419, 0.6915);
TextDrawAlignment(AutoSalon_TD[39], 1);
TextDrawColor(AutoSalon_TD[39], -1768515841);
TextDrawBackgroundColor(AutoSalon_TD[39], 255);
TextDrawFont(AutoSalon_TD[39], 1);
TextDrawSetProportional(AutoSalon_TD[39], 1);
TextDrawSetShadow(AutoSalon_TD[39], 0);

AutoSalon_TD[40] = TextDrawCreate(544.8659, 296.0357, "LD_SPAC:white"); // range 3 box - "exit"
TextDrawTextSize(AutoSalon_TD[40], 56.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[40], 1);
TextDrawColor(AutoSalon_TD[40], 522133503);
TextDrawBackgroundColor(AutoSalon_TD[40], 255);
TextDrawFont(AutoSalon_TD[40], 4);
TextDrawSetProportional(AutoSalon_TD[40], 0);
TextDrawSetShadow(AutoSalon_TD[40], 0);

AutoSalon_TD[41] = TextDrawCreate(572.5321, 298.6799, "EXIT"); // range 3 tx - "exit"
TextDrawLetterSize(AutoSalon_TD[41], 0.1972, 0.9236);
TextDrawTextSize(AutoSalon_TD[41], 56.0000, 14.0000);
TextDrawAlignment(AutoSalon_TD[41], 2);
TextDrawColor(AutoSalon_TD[41], -1768515841);
TextDrawBackgroundColor(AutoSalon_TD[41], 255);
TextDrawFont(AutoSalon_TD[41], 1);
TextDrawSetProportional(AutoSalon_TD[41], 1);
TextDrawSetShadow(AutoSalon_TD[41], 0);
TextDrawSetSelectable(AutoSalon_TD[41], true);