dm_TD[0] = TextDrawCreate(546.7999, 366.0577, "LD_SPAC:white"); // пусто
TextDrawTextSize(dm_TD[0], 40.0000, 14.0000);
TextDrawAlignment(dm_TD[0], 1);
TextDrawColor(dm_TD[0], 252645375);
TextDrawBackgroundColor(dm_TD[0], 255);
TextDrawFont(dm_TD[0], 4);
TextDrawSetProportional(dm_TD[0], 0);
TextDrawSetShadow(dm_TD[0], 0);

dm_TD[1] = TextDrawCreate(573.6000, 360.8822, "LD_BEAT:chit"); // пусто
TextDrawTextSize(dm_TD[1], 21.0000, 24.0000);
TextDrawAlignment(dm_TD[1], 1);
TextDrawColor(dm_TD[1], -1523963137);
TextDrawBackgroundColor(dm_TD[1], 255);
TextDrawFont(dm_TD[1], 4);
TextDrawSetProportional(dm_TD[1], 0);
TextDrawSetShadow(dm_TD[1], 0);

dm_TD[2] = TextDrawCreate(556.6001, 367.5066, "KILL"); // пусто
TextDrawLetterSize(dm_TD[2], 0.2128, 1.0872);
TextDrawAlignment(dm_TD[2], 1);
TextDrawColor(dm_TD[2], -1);
TextDrawBackgroundColor(dm_TD[2], 255);
TextDrawFont(dm_TD[2], 1);
TextDrawSetProportional(dm_TD[2], 1);
TextDrawSetShadow(dm_TD[2], 0);

dm_TD[3] = TextDrawCreate(546.8000, 383.6182, "LD_SPAC:white"); // пусто
TextDrawTextSize(dm_TD[3], 40.0000, 14.0000);
TextDrawAlignment(dm_TD[3], 1);
TextDrawColor(dm_TD[3], 252645375);
TextDrawBackgroundColor(dm_TD[3], 255);
TextDrawFont(dm_TD[3], 4);
TextDrawSetProportional(dm_TD[3], 0);
TextDrawSetShadow(dm_TD[3], 0);

dm_TD[4] = TextDrawCreate(573.6000, 378.5022, "LD_BEAT:chit"); // пусто
TextDrawTextSize(dm_TD[4], 21.0000, 24.0000);
TextDrawAlignment(dm_TD[4], 1);
TextDrawColor(dm_TD[4], -1523963137);
TextDrawBackgroundColor(dm_TD[4], 255);
TextDrawFont(dm_TD[4], 4);
TextDrawSetProportional(dm_TD[4], 0);
TextDrawSetShadow(dm_TD[4], 0);

dm_TD[5] = TextDrawCreate(553.2999, 385.3355, "DEATH"); // пусто
TextDrawLetterSize(dm_TD[5], 0.2128, 1.0872);
TextDrawAlignment(dm_TD[5], 1);
TextDrawColor(dm_TD[5], -1);
TextDrawBackgroundColor(dm_TD[5], 255);
TextDrawFont(dm_TD[5], 1);
TextDrawSetProportional(dm_TD[5], 1);
TextDrawSetShadow(dm_TD[5], 0);