eshop_TD[0] = TextDrawCreate(224.7071, 147.4165, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[0], 110.0000, 229.0000);
TextDrawAlignment(eshop_TD[0], 1);
TextDrawColor(eshop_TD[0], 353703423);
TextDrawBackgroundColor(eshop_TD[0], 255);
TextDrawFont(eshop_TD[0], 4);
TextDrawSetProportional(eshop_TD[0], 0);
TextDrawSetShadow(eshop_TD[0], 0);

eshop_TD[1] = TextDrawCreate(227.9868, 177.7500, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[1], 102.0000, 192.0000);
TextDrawAlignment(eshop_TD[1], 1);
TextDrawColor(eshop_TD[1], 623191551);
TextDrawBackgroundColor(eshop_TD[1], 255);
TextDrawFont(eshop_TD[1], 4);
TextDrawSetProportional(eshop_TD[1], 0);
TextDrawSetShadow(eshop_TD[1], 0);

eshop_TD[2] = TextDrawCreate(215.3368, 132.2498, ""); // ïóñòî
TextDrawTextSize(eshop_TD[2], 27.0000, 31.0000);
TextDrawAlignment(eshop_TD[2], 1);
TextDrawColor(eshop_TD[2], -1);
TextDrawBackgroundColor(eshop_TD[2], 572661504);
TextDrawFont(eshop_TD[2], 5);
TextDrawSetProportional(eshop_TD[2], 0);
TextDrawSetShadow(eshop_TD[2], 0);
TextDrawSetPreviewModel(eshop_TD[2], 19341);
TextDrawSetPreviewRot(eshop_TD[2], 0.0000, 20.0000, 0.0000, 1.0000);

eshop_TD[3] = TextDrawCreate(227.6867, 164.3332, "EASTER_SHOP"); // ïóñòî
TextDrawLetterSize(eshop_TD[3], 0.2504, 1.1857);
TextDrawAlignment(eshop_TD[3], 1);
TextDrawColor(eshop_TD[3], -1);
TextDrawBackgroundColor(eshop_TD[3], 255);
TextDrawFont(eshop_TD[3], 1);
TextDrawSetProportional(eshop_TD[3], 1);
TextDrawSetShadow(eshop_TD[3], 0);

eshop_TD[4] = TextDrawCreate(229.8609, 181.2498, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[4], 98.0000, 29.0000);
TextDrawAlignment(eshop_TD[4], 1);
TextDrawColor(eshop_TD[4], 1077952767);
TextDrawBackgroundColor(eshop_TD[4], 255);
TextDrawFont(eshop_TD[4], 4);
TextDrawSetProportional(eshop_TD[4], 0);
TextDrawSetShadow(eshop_TD[4], 0);
TextDrawSetSelectable(eshop_TD[4], true);

eshop_TD[5] = TextDrawCreate(230.7978, 182.4165, ""); // ïóñòî
TextDrawTextSize(eshop_TD[5], 27.0000, 27.0000);
TextDrawAlignment(eshop_TD[5], 1);
TextDrawColor(eshop_TD[5], -1);
TextDrawBackgroundColor(eshop_TD[5], 623191551);
TextDrawFont(eshop_TD[5], 5);
TextDrawSetProportional(eshop_TD[5], 0);
TextDrawSetShadow(eshop_TD[5], 0);
TextDrawSetPreviewModel(eshop_TD[5], 1274);
TextDrawSetPreviewRot(eshop_TD[5], 0.0000, 0.0000, 180.0000, 1.0000);

eshop_TD[6] = TextDrawCreate(259.0775, 181.8332, "Money"); // ïóñòî
TextDrawLetterSize(eshop_TD[6], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[6], 1);
TextDrawColor(eshop_TD[6], -1);
TextDrawBackgroundColor(eshop_TD[6], 255);
TextDrawFont(eshop_TD[6], 1);
TextDrawSetProportional(eshop_TD[6], 1);
TextDrawSetShadow(eshop_TD[6], 0);

eshop_TD[7] = TextDrawCreate(258.6090, 193.4998, "50.000$"); // ïóñòî
TextDrawLetterSize(eshop_TD[7], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[7], 1);
TextDrawColor(eshop_TD[7], -1);
TextDrawBackgroundColor(eshop_TD[7], 255);
TextDrawFont(eshop_TD[7], 1);
TextDrawSetProportional(eshop_TD[7], 1);
TextDrawSetShadow(eshop_TD[7], 0);

eshop_TD[8] = TextDrawCreate(229.8609, 212.1665, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[8], 98.0000, 29.0000);
TextDrawAlignment(eshop_TD[8], 1);
TextDrawColor(eshop_TD[8], 1077952767);
TextDrawBackgroundColor(eshop_TD[8], 255);
TextDrawFont(eshop_TD[8], 4);
TextDrawSetProportional(eshop_TD[8], 0);
TextDrawSetShadow(eshop_TD[8], 0);
TextDrawSetSelectable(eshop_TD[8], true);

eshop_TD[9] = TextDrawCreate(230.7978, 212.9835, ""); // ïóñòî
TextDrawTextSize(eshop_TD[9], 27.0000, 27.0000);
TextDrawAlignment(eshop_TD[9], 1);
TextDrawColor(eshop_TD[9], -1);
TextDrawBackgroundColor(eshop_TD[9], 623191551);
TextDrawFont(eshop_TD[9], 5);
TextDrawSetProportional(eshop_TD[9], 0);
TextDrawSetShadow(eshop_TD[9], 0);
TextDrawSetPreviewModel(eshop_TD[9], 1274);
TextDrawSetPreviewRot(eshop_TD[9], 0.0000, 0.0000, 180.0000, 1.0000);

eshop_TD[10] = TextDrawCreate(259.0775, 212.1665, "Money"); // ïóñòî
TextDrawLetterSize(eshop_TD[10], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[10], 1);
TextDrawColor(eshop_TD[10], -1);
TextDrawBackgroundColor(eshop_TD[10], 255);
TextDrawFont(eshop_TD[10], 1);
TextDrawSetProportional(eshop_TD[10], 1);
TextDrawSetShadow(eshop_TD[10], 0);

eshop_TD[11] = TextDrawCreate(259.0775, 223.8332, "200.000$"); // ïóñòî
TextDrawLetterSize(eshop_TD[11], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[11], 1);
TextDrawColor(eshop_TD[11], -1);
TextDrawBackgroundColor(eshop_TD[11], 255);
TextDrawFont(eshop_TD[11], 1);
TextDrawSetProportional(eshop_TD[11], 1);
TextDrawSetShadow(eshop_TD[11], 0);

eshop_TD[12] = TextDrawCreate(229.8609, 242.9998, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[12], 98.0000, 29.0000);
TextDrawAlignment(eshop_TD[12], 1);
TextDrawColor(eshop_TD[12], 1077952767);
TextDrawBackgroundColor(eshop_TD[12], 255);
TextDrawFont(eshop_TD[12], 4);
TextDrawSetProportional(eshop_TD[12], 0);
TextDrawSetShadow(eshop_TD[12], 0);
TextDrawSetSelectable(eshop_TD[12], true);

eshop_TD[13] = TextDrawCreate(230.7978, 243.9172, ""); // ïóñòî
TextDrawTextSize(eshop_TD[13], 27.0000, 27.0000);
TextDrawAlignment(eshop_TD[13], 1);
TextDrawColor(eshop_TD[13], -1);
TextDrawBackgroundColor(eshop_TD[13], 623191551);
TextDrawFont(eshop_TD[13], 5);
TextDrawSetProportional(eshop_TD[13], 0);
TextDrawSetShadow(eshop_TD[13], 0);
TextDrawSetPreviewModel(eshop_TD[13], 1239);
TextDrawSetPreviewRot(eshop_TD[13], 0.0000, 0.0000, 180.0000, 1.0000);

eshop_TD[14] = TextDrawCreate(259.5461, 243.0832, "Level"); // ïóñòî
TextDrawLetterSize(eshop_TD[14], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[14], 1);
TextDrawColor(eshop_TD[14], -1);
TextDrawBackgroundColor(eshop_TD[14], 255);
TextDrawFont(eshop_TD[14], 1);
TextDrawSetProportional(eshop_TD[14], 1);
TextDrawSetShadow(eshop_TD[14], 0);

eshop_TD[15] = TextDrawCreate(259.5461, 254.1665, "3_LVL"); // ïóñòî
TextDrawLetterSize(eshop_TD[15], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[15], 1);
TextDrawColor(eshop_TD[15], -1);
TextDrawBackgroundColor(eshop_TD[15], 255);
TextDrawFont(eshop_TD[15], 1);
TextDrawSetProportional(eshop_TD[15], 1);
TextDrawSetShadow(eshop_TD[15], 0);

eshop_TD[16] = TextDrawCreate(229.9293, 273.6333, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[16], 98.0000, 29.0000);
TextDrawAlignment(eshop_TD[16], 1);
TextDrawColor(eshop_TD[16], 1077952767);
TextDrawBackgroundColor(eshop_TD[16], 255);
TextDrawFont(eshop_TD[16], 4);
TextDrawSetProportional(eshop_TD[16], 0);
TextDrawSetShadow(eshop_TD[16], 0);
TextDrawSetSelectable(eshop_TD[16], true);

eshop_TD[17] = TextDrawCreate(230.8348, 274.4675, ""); // ïóñòî
TextDrawTextSize(eshop_TD[17], 27.0000, 27.0000);
TextDrawAlignment(eshop_TD[17], 1);
TextDrawColor(eshop_TD[17], -1);
TextDrawBackgroundColor(eshop_TD[17], 623191551);
TextDrawFont(eshop_TD[17], 5);
TextDrawSetProportional(eshop_TD[17], 0);
TextDrawSetShadow(eshop_TD[17], 0);
TextDrawSetPreviewModel(eshop_TD[17], 1277);
TextDrawSetPreviewRot(eshop_TD[17], 0.0000, 0.0000, 180.0000, 1.0000);

eshop_TD[18] = TextDrawCreate(259.0775, 274.5834, "VIP"); // ïóñòî
TextDrawLetterSize(eshop_TD[18], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[18], 1);
TextDrawColor(eshop_TD[18], -1);
TextDrawBackgroundColor(eshop_TD[18], 255);
TextDrawFont(eshop_TD[18], 1);
TextDrawSetProportional(eshop_TD[18], 1);
TextDrawSetShadow(eshop_TD[18], 0);

eshop_TD[19] = TextDrawCreate(259.0775, 286.8334, "Silver_Vip_-_15days"); // ïóñòî
TextDrawLetterSize(eshop_TD[19], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[19], 1);
TextDrawColor(eshop_TD[19], -1);
TextDrawBackgroundColor(eshop_TD[19], 255);
TextDrawFont(eshop_TD[19], 1);
TextDrawSetProportional(eshop_TD[19], 1);
TextDrawSetShadow(eshop_TD[19], 0);

eshop_TD[20] = TextDrawCreate(229.9293, 303.9498, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[20], 98.0000, 29.0000);
TextDrawAlignment(eshop_TD[20], 1);
TextDrawColor(eshop_TD[20], 1077952767);
TextDrawBackgroundColor(eshop_TD[20], 255);
TextDrawFont(eshop_TD[20], 4);
TextDrawSetProportional(eshop_TD[20], 0);
TextDrawSetShadow(eshop_TD[20], 0);
TextDrawSetSelectable(eshop_TD[20], true);

eshop_TD[21] = TextDrawCreate(230.8348, 305.3677, ""); // ïóñòî
TextDrawTextSize(eshop_TD[21], 27.0000, 27.0000);
TextDrawAlignment(eshop_TD[21], 1);
TextDrawColor(eshop_TD[21], -1);
TextDrawBackgroundColor(eshop_TD[21], 623191551);
TextDrawFont(eshop_TD[21], 5);
TextDrawSetProportional(eshop_TD[21], 0);
TextDrawSetShadow(eshop_TD[21], 0);
TextDrawSetPreviewModel(eshop_TD[21], 3013);
TextDrawSetPreviewRot(eshop_TD[21], -20.0000, 0.0000, 40.0000, 1.0000);

eshop_TD[22] = TextDrawCreate(260.0145, 304.9166, "Case"); // ïóñòî
TextDrawLetterSize(eshop_TD[22], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[22], 1);
TextDrawColor(eshop_TD[22], -1);
TextDrawBackgroundColor(eshop_TD[22], 255);
TextDrawFont(eshop_TD[22], 1);
TextDrawSetProportional(eshop_TD[22], 1);
TextDrawSetShadow(eshop_TD[22], 0);

eshop_TD[23] = TextDrawCreate(259.5461, 315.4168, "Magic_Case"); // ïóñòî
TextDrawLetterSize(eshop_TD[23], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[23], 1);
TextDrawColor(eshop_TD[23], -1);
TextDrawBackgroundColor(eshop_TD[23], 255);
TextDrawFont(eshop_TD[23], 1);
TextDrawSetProportional(eshop_TD[23], 1);
TextDrawSetShadow(eshop_TD[23], 0);

eshop_TD[24] = TextDrawCreate(229.9293, 334.6669, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[24], 98.0000, 29.0000);
TextDrawAlignment(eshop_TD[24], 1);
TextDrawColor(eshop_TD[24], 1077952767);
TextDrawBackgroundColor(eshop_TD[24], 255);
TextDrawFont(eshop_TD[24], 4);
TextDrawSetProportional(eshop_TD[24], 0);
TextDrawSetShadow(eshop_TD[24], 0);
TextDrawSetSelectable(eshop_TD[24], true);

eshop_TD[25] = TextDrawCreate(230.8348, 335.7012, ""); // ïóñòî
TextDrawTextSize(eshop_TD[25], 27.0000, 27.0000);
TextDrawAlignment(eshop_TD[25], 1);
TextDrawColor(eshop_TD[25], -1);
TextDrawBackgroundColor(eshop_TD[25], 623191551);
TextDrawFont(eshop_TD[25], 5);
TextDrawSetProportional(eshop_TD[25], 0);
TextDrawSetShadow(eshop_TD[25], 0);
TextDrawSetPreviewModel(eshop_TD[25], 19918);
TextDrawSetPreviewRot(eshop_TD[25], -20.0000, 0.0000, 40.0000, 1.0000);

eshop_TD[26] = TextDrawCreate(259.5462, 335.2500, "Case"); // ïóñòî
TextDrawLetterSize(eshop_TD[26], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[26], 1);
TextDrawColor(eshop_TD[26], -1);
TextDrawBackgroundColor(eshop_TD[26], 255);
TextDrawFont(eshop_TD[26], 1);
TextDrawSetProportional(eshop_TD[26], 1);
TextDrawSetShadow(eshop_TD[26], 0);

eshop_TD[27] = TextDrawCreate(260.0147, 346.3334, "Titany_Case"); // ïóñòî
TextDrawLetterSize(eshop_TD[27], 0.2205, 1.2091);
TextDrawAlignment(eshop_TD[27], 1);
TextDrawColor(eshop_TD[27], -1);
TextDrawBackgroundColor(eshop_TD[27], 255);
TextDrawFont(eshop_TD[27], 1);
TextDrawSetProportional(eshop_TD[27], 1);
TextDrawSetShadow(eshop_TD[27], 0);

eshop_TD[28] = TextDrawCreate(335.7467, 147.4167, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[28], 131.0000, 120.0000);
TextDrawAlignment(eshop_TD[28], 1);
TextDrawColor(eshop_TD[28], 353703423);
TextDrawBackgroundColor(eshop_TD[28], 255);
TextDrawFont(eshop_TD[28], 4);
TextDrawSetProportional(eshop_TD[28], 0);
TextDrawSetShadow(eshop_TD[28], 0);

eshop_TD[29] = TextDrawCreate(339.0263, 162.5832, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[29], 124.0000, 80.0000);
TextDrawAlignment(eshop_TD[29], 1);
TextDrawColor(eshop_TD[29], 623191551);
TextDrawBackgroundColor(eshop_TD[29], 255);
TextDrawFont(eshop_TD[29], 4);
TextDrawSetProportional(eshop_TD[29], 0);
TextDrawSetShadow(eshop_TD[29], 0);

eshop_TD[30] = TextDrawCreate(416.5006, 206.3332, "PREVIEW"); // ïóñòî
TextDrawLetterSize(eshop_TD[30], 0.1979, 1.0923);
TextDrawAlignment(eshop_TD[30], 1);
TextDrawColor(eshop_TD[30], -1);
TextDrawBackgroundColor(eshop_TD[30], 255);
TextDrawFont(eshop_TD[30], 1);
TextDrawSetProportional(eshop_TD[30], 1);
TextDrawSetShadow(eshop_TD[30], 0);

eshop_TD[31] = TextDrawCreate(414.9266, 244.7001, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[31], 48.0000, 18.0000);
TextDrawAlignment(eshop_TD[31], 1);
TextDrawColor(eshop_TD[31], 1169399295);
TextDrawBackgroundColor(eshop_TD[31], 255);
TextDrawFont(eshop_TD[31], 4);
TextDrawSetProportional(eshop_TD[31], 0);
TextDrawSetShadow(eshop_TD[31], 0);
TextDrawSetSelectable(eshop_TD[31], true);

eshop_TD[32] = TextDrawCreate(364.7947, 244.7001, "LD_SPAC:white"); // ïóñòî
TextDrawTextSize(eshop_TD[32], 48.0000, 18.0000);
TextDrawAlignment(eshop_TD[32], 1);
TextDrawColor(eshop_TD[32], 1169399295);
TextDrawBackgroundColor(eshop_TD[32], 255);
TextDrawFont(eshop_TD[32], 4);
TextDrawSetProportional(eshop_TD[32], 0);
TextDrawSetShadow(eshop_TD[32], 0);
TextDrawSetSelectable(eshop_TD[32], true);

eshop_TD[33] = TextDrawCreate(387.9895, 248.8500, "EXCHANGE"); // ïóñòî
TextDrawLetterSize(eshop_TD[33], 0.1960, 1.1158);
TextDrawAlignment(eshop_TD[33], 2);
TextDrawColor(eshop_TD[33], -1);
TextDrawBackgroundColor(eshop_TD[33], 255);
TextDrawFont(eshop_TD[33], 1);
TextDrawSetProportional(eshop_TD[33], 1);
TextDrawSetShadow(eshop_TD[33], 0);

eshop_TD[34] = TextDrawCreate(438.0267, 249.1333, "CLOSE"); // ïóñòî
TextDrawLetterSize(eshop_TD[34], 0.1960, 1.1158);
TextDrawAlignment(eshop_TD[34], 2);
TextDrawColor(eshop_TD[34], -1);
TextDrawBackgroundColor(eshop_TD[34], 255);
TextDrawFont(eshop_TD[34], 1);
TextDrawSetProportional(eshop_TD[34], 1);
TextDrawSetShadow(eshop_TD[34], 0);

eshop_TD[35] = TextDrawCreate(339.6632, 150.3332, "CASHIER"); // ïóñòî
TextDrawLetterSize(eshop_TD[35], 0.2345, 1.2323);
TextDrawAlignment(eshop_TD[35], 1);
TextDrawColor(eshop_TD[35], -1);
TextDrawBackgroundColor(eshop_TD[35], 255);
TextDrawFont(eshop_TD[35], 1);
TextDrawSetProportional(eshop_TD[35], 1);
TextDrawSetShadow(eshop_TD[35], 0);