event_TD[0] = TextDrawCreate(583.3999, 214.2356, "LD_SPAC:white"); // пусто
TextDrawTextSize(event_TD[0], 59.0000, 19.0000);
TextDrawAlignment(event_TD[0], 1);
TextDrawColor(event_TD[0], -1523963137);
TextDrawBackgroundColor(event_TD[0], 255);
TextDrawFont(event_TD[0], 4);
TextDrawSetProportional(event_TD[0], 0);
TextDrawSetShadow(event_TD[0], 0);

event_TD[1] = TextDrawCreate(569.0003, 205.0800, ""); // пусто
TextDrawTextSize(event_TD[1], 31.0000, 32.0000);
TextDrawAlignment(event_TD[1], 1);
TextDrawColor(event_TD[1], -1523963137);
TextDrawBackgroundColor(event_TD[1], 572661504);
TextDrawFont(event_TD[1], 5);
TextDrawSetProportional(event_TD[1], 0);
TextDrawSetShadow(event_TD[1], 0);
TextDrawSetPreviewModel(event_TD[1], 19177);
TextDrawSetPreviewRot(event_TD[1], 0.0000, 10.0000, 0.0000, 0.2000);

event_TD[2] = TextDrawCreate(584.5997, 215.7334, "LD_SPAC:white"); // пусто
TextDrawTextSize(event_TD[2], 59.0000, 16.0000);
TextDrawAlignment(event_TD[2], 1);
TextDrawColor(event_TD[2], 252645375);
TextDrawBackgroundColor(event_TD[2], 255);
TextDrawFont(event_TD[2], 4);
TextDrawSetProportional(event_TD[2], 0);
TextDrawSetShadow(event_TD[2], 0);

event_TD[3] = TextDrawCreate(570.6001, 207.7711, ""); // пусто
TextDrawTextSize(event_TD[3], 30.0000, 28.0000);
TextDrawAlignment(event_TD[3], 1);
TextDrawColor(event_TD[3], 252645375);
TextDrawBackgroundColor(event_TD[3], 572661504);
TextDrawFont(event_TD[3], 5);
TextDrawSetProportional(event_TD[3], 0);
TextDrawSetShadow(event_TD[3], 0);
TextDrawSetPreviewModel(event_TD[3], 19177);
TextDrawSetPreviewRot(event_TD[3], 0.0000, 10.0000, 0.0000, 0.2000);

event_TD[4] = TextDrawCreate(610.0000, 218.3733, "EVENT_NAME"); // пусто
TextDrawLetterSize(event_TD[4], 0.1908, 1.1022);
TextDrawTextSize(event_TD[4], 14.0000, 14.0000);
TextDrawAlignment(event_TD[4], 2);
TextDrawColor(event_TD[4], -1);
TextDrawBackgroundColor(event_TD[4], 255);
TextDrawFont(event_TD[4], 1);
TextDrawSetProportional(event_TD[4], 1);
TextDrawSetShadow(event_TD[4], 0);

event_TD[5] = TextDrawCreate(565.4004, 234.6444, "LD_SPAC:white"); // пусто
TextDrawTextSize(event_TD[5], 76.0000, 15.0000);
TextDrawAlignment(event_TD[5], 1);
TextDrawColor(event_TD[5], -1523963137);
TextDrawBackgroundColor(event_TD[5], 255);
TextDrawFont(event_TD[5], 4);
TextDrawSetProportional(event_TD[5], 0);
TextDrawSetShadow(event_TD[5], 0);

event_TD[6] = TextDrawCreate(553.7002, 227.3799, ""); // пусто
TextDrawTextSize(event_TD[6], 24.0000, 26.0000);
TextDrawAlignment(event_TD[6], 1);
TextDrawColor(event_TD[6], -1523963137);
TextDrawBackgroundColor(event_TD[6], 572661504);
TextDrawFont(event_TD[6], 5);
TextDrawSetProportional(event_TD[6], 0);
TextDrawSetShadow(event_TD[6], 0);
TextDrawSetPreviewModel(event_TD[6], 19177);
TextDrawSetPreviewRot(event_TD[6], 0.0000, 10.0000, 0.0000, 0.2000);

event_TD[7] = TextDrawCreate(557.3004, 228.8755, ""); // пусто
TextDrawTextSize(event_TD[7], 19.0000, 23.0000);
TextDrawAlignment(event_TD[7], 1);
TextDrawColor(event_TD[7], 252645375);
TextDrawBackgroundColor(event_TD[7], 572661504);
TextDrawFont(event_TD[7], 5);
TextDrawSetProportional(event_TD[7], 0);
TextDrawSetShadow(event_TD[7], 0);
TextDrawSetPreviewModel(event_TD[7], 19177);
TextDrawSetPreviewRot(event_TD[7], 0.0000, 10.0000, 0.0000, 0.2000);

event_TD[8] = TextDrawCreate(566.5997, 235.6400, "LD_SPAC:white"); // пусто
TextDrawTextSize(event_TD[8], 75.0000, 13.0000);
TextDrawAlignment(event_TD[8], 1);
TextDrawColor(event_TD[8], 252645375);
TextDrawBackgroundColor(event_TD[8], 255);
TextDrawFont(event_TD[8], 4);
TextDrawSetProportional(event_TD[8], 0);
TextDrawSetShadow(event_TD[8], 0);

event_TD[9] = TextDrawCreate(591.1010, 229.4666, "LD_BEAT:chit"); // пусто
TextDrawTextSize(event_TD[9], 23.0000, 27.0000);
TextDrawAlignment(event_TD[9], 1);
TextDrawColor(event_TD[9], -1523963137);
TextDrawBackgroundColor(event_TD[9], 255);
TextDrawFont(event_TD[9], 4);
TextDrawSetProportional(event_TD[9], 0);
TextDrawSetShadow(event_TD[9], 0);

event_TD[10] = TextDrawCreate(567.8000, 238.2844, "TP_EVENT"); // пусто
TextDrawLetterSize(event_TD[10], 0.1723, 0.9080);
TextDrawAlignment(event_TD[10], 1);
TextDrawColor(event_TD[10], -1);
TextDrawBackgroundColor(event_TD[10], 255);
TextDrawFont(event_TD[10], 1);
TextDrawSetProportional(event_TD[10], 1);
TextDrawSetShadow(event_TD[10], 0);

event_TD[11] = TextDrawCreate(602.5999, 237.6844, "20"); // пусто
TextDrawLetterSize(event_TD[11], 0.2203, 1.0922);
TextDrawAlignment(event_TD[11], 2);
TextDrawColor(event_TD[11], -1);
TextDrawBackgroundColor(event_TD[11], 255);
TextDrawFont(event_TD[11], 3);
TextDrawSetProportional(event_TD[11], 1);
TextDrawSetShadow(event_TD[11], 0);

event_TD[12] = TextDrawCreate(613.8001, 238.4822, "/GOEVENT"); // пусто
TextDrawLetterSize(event_TD[12], 0.1487, 0.8782);
TextDrawAlignment(event_TD[12], 1);
TextDrawColor(event_TD[12], -1);
TextDrawBackgroundColor(event_TD[12], 255);
TextDrawFont(event_TD[12], 1);
TextDrawSetProportional(event_TD[12], 1);
TextDrawSetShadow(event_TD[12], 0);