MainMenu_TD[0] = TextDrawCreate(222.4998, 92.5184, "Box"); // ?????
TextDrawLetterSize(MainMenu_TD[0], 0.0000, 22.0095);
TextDrawTextSize(MainMenu_TD[0], 492.6787, 0.0000);
TextDrawAlignment(MainMenu_TD[0], 1);
TextDrawColor(MainMenu_TD[0], -1);
TextDrawUseBox(MainMenu_TD[0], 1);
TextDrawBoxColor(MainMenu_TD[0], 255);
TextDrawBackgroundColor(MainMenu_TD[0], 255);
TextDrawFont(MainMenu_TD[0], 1);
TextDrawSetProportional(MainMenu_TD[0], 1);
TextDrawSetShadow(MainMenu_TD[0], 0);

MainMenu_TD[1] = TextDrawCreate(231.6665, 102.3703, "Box"); // ?????
TextDrawLetterSize(MainMenu_TD[1], 0.0000, 13.3332);
TextDrawTextSize(MainMenu_TD[1], 322.1892, 0.0000);
TextDrawAlignment(MainMenu_TD[1], 1);
TextDrawColor(MainMenu_TD[1], -1);
TextDrawUseBox(MainMenu_TD[1], 1);
TextDrawBoxColor(MainMenu_TD[1], 286331391);
TextDrawBackgroundColor(MainMenu_TD[1], 255);
TextDrawFont(MainMenu_TD[1], 1);
TextDrawSetProportional(MainMenu_TD[1], 1);
TextDrawSetShadow(MainMenu_TD[1], 0);

MainMenu_TD[2] = TextDrawCreate(230.1000, 230.5632, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[2], 46.0000, 17.0000);
TextDrawAlignment(MainMenu_TD[2], 1);
TextDrawColor(MainMenu_TD[2], 286331391);
TextDrawBackgroundColor(MainMenu_TD[2], 255);
TextDrawFont(MainMenu_TD[2], 4);
TextDrawSetProportional(MainMenu_TD[2], 0);
TextDrawSetShadow(MainMenu_TD[2], 0);
TextDrawSetSelectable(MainMenu_TD[2], true);

MainMenu_TD[3] = TextDrawCreate(277.4334, 230.5634, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[3], 46.0000, 17.0000);
TextDrawAlignment(MainMenu_TD[3], 1);
TextDrawColor(MainMenu_TD[3], 286331391);
TextDrawBackgroundColor(MainMenu_TD[3], 255);
TextDrawFont(MainMenu_TD[3], 4);
TextDrawSetProportional(MainMenu_TD[3], 0);
TextDrawSetShadow(MainMenu_TD[3], 0);
TextDrawSetSelectable(MainMenu_TD[3], true);

MainMenu_TD[4] = TextDrawCreate(230.0500, 249.6006, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[4], 46.0000, 17.0000);
TextDrawAlignment(MainMenu_TD[4], 1);
TextDrawColor(MainMenu_TD[4], 286331391);
TextDrawBackgroundColor(MainMenu_TD[4], 255);
TextDrawFont(MainMenu_TD[4], 4);
TextDrawSetProportional(MainMenu_TD[4], 0);
TextDrawSetShadow(MainMenu_TD[4], 0);
TextDrawSetSelectable(MainMenu_TD[4], true);

MainMenu_TD[5] = TextDrawCreate(277.3999, 249.6006, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[5], 46.0000, 17.0000);
TextDrawAlignment(MainMenu_TD[5], 1);
TextDrawColor(MainMenu_TD[5], 286331391);
TextDrawBackgroundColor(MainMenu_TD[5], 255);
TextDrawFont(MainMenu_TD[5], 4);
TextDrawSetProportional(MainMenu_TD[5], 0);
TextDrawSetShadow(MainMenu_TD[5], 0);
TextDrawSetSelectable(MainMenu_TD[5], true);

MainMenu_TD[6] = TextDrawCreate(230.0166, 268.7637, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[6], 46.0000, 17.0000);
TextDrawAlignment(MainMenu_TD[6], 1);
TextDrawColor(MainMenu_TD[6], 286331391);
TextDrawBackgroundColor(MainMenu_TD[6], 255);
TextDrawFont(MainMenu_TD[6], 4);
TextDrawSetProportional(MainMenu_TD[6], 0);
TextDrawSetShadow(MainMenu_TD[6], 0);
TextDrawSetSelectable(MainMenu_TD[6], true);

MainMenu_TD[7] = TextDrawCreate(277.6195, 268.7637, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[7], 46.0000, 17.0000);
TextDrawAlignment(MainMenu_TD[7], 1);
TextDrawColor(MainMenu_TD[7], 286331391);
TextDrawBackgroundColor(MainMenu_TD[7], 255);
TextDrawFont(MainMenu_TD[7], 4);
TextDrawSetProportional(MainMenu_TD[7], 0);
TextDrawSetShadow(MainMenu_TD[7], 0);
TextDrawSetSelectable(MainMenu_TD[7], true);

MainMenu_TD[8] = TextDrawCreate(252.7664, 234.0740, "MENU"); // ?????
TextDrawLetterSize(MainMenu_TD[8], 0.1238, 0.9362);
TextDrawAlignment(MainMenu_TD[8], 2);
TextDrawColor(MainMenu_TD[8], -741092353);
TextDrawBackgroundColor(MainMenu_TD[8], 255);
TextDrawFont(MainMenu_TD[8], 2);
TextDrawSetProportional(MainMenu_TD[8], 1);
TextDrawSetShadow(MainMenu_TD[8], 0);

MainMenu_TD[9] = TextDrawCreate(302.0833, 233.7111, "COMMANDS"); // ?????
TextDrawLetterSize(MainMenu_TD[9], 0.1238, 0.9362);
TextDrawAlignment(MainMenu_TD[9], 2);
TextDrawColor(MainMenu_TD[9], -741092353);
TextDrawBackgroundColor(MainMenu_TD[9], 255);
TextDrawFont(MainMenu_TD[9], 2);
TextDrawSetProportional(MainMenu_TD[9], 1);
TextDrawSetShadow(MainMenu_TD[9], 0);

MainMenu_TD[10] = TextDrawCreate(253.3332, 253.7778, "SETTINGS"); // ?????
TextDrawLetterSize(MainMenu_TD[10], 0.1238, 0.9362);
TextDrawAlignment(MainMenu_TD[10], 2);
TextDrawColor(MainMenu_TD[10], -741092353);
TextDrawBackgroundColor(MainMenu_TD[10], 255);
TextDrawFont(MainMenu_TD[10], 2);
TextDrawSetProportional(MainMenu_TD[10], 1);
TextDrawSetShadow(MainMenu_TD[10], 0);

MainMenu_TD[11] = TextDrawCreate(300.8499, 253.7778, "SECURITY"); // ?????
TextDrawLetterSize(MainMenu_TD[11], 0.1238, 0.9362);
TextDrawAlignment(MainMenu_TD[11], 2);
TextDrawColor(MainMenu_TD[11], -741092353);
TextDrawBackgroundColor(MainMenu_TD[11], 255);
TextDrawFont(MainMenu_TD[11], 2);
TextDrawSetProportional(MainMenu_TD[11], 1);
TextDrawSetShadow(MainMenu_TD[11], 0);

MainMenu_TD[12] = TextDrawCreate(252.9165, 272.9630, "REPORT"); // ?????
TextDrawLetterSize(MainMenu_TD[12], 0.1238, 0.9362);
TextDrawAlignment(MainMenu_TD[12], 2);
TextDrawColor(MainMenu_TD[12], -741092353);
TextDrawBackgroundColor(MainMenu_TD[12], 255);
TextDrawFont(MainMenu_TD[12], 2);
TextDrawSetProportional(MainMenu_TD[12], 1);
TextDrawSetShadow(MainMenu_TD[12], 0);

MainMenu_TD[13] = TextDrawCreate(301.2499, 272.4443, "PROMOCODE"); // ?????
TextDrawLetterSize(MainMenu_TD[13], 0.1238, 0.9362);
TextDrawAlignment(MainMenu_TD[13], 2);
TextDrawColor(MainMenu_TD[13], -741092353);
TextDrawBackgroundColor(MainMenu_TD[13], 255);
TextDrawFont(MainMenu_TD[13], 2);
TextDrawSetProportional(MainMenu_TD[13], 1);
TextDrawSetShadow(MainMenu_TD[13], 0);

MainMenu_TD[14] = TextDrawCreate(266.3175, 104.0736, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[14], 26.0000, 27.0000);
TextDrawAlignment(MainMenu_TD[14], 1);
TextDrawColor(MainMenu_TD[14], 255);
TextDrawBackgroundColor(MainMenu_TD[14], 255);
TextDrawFont(MainMenu_TD[14], 4);
TextDrawSetProportional(MainMenu_TD[14], 0);
TextDrawSetShadow(MainMenu_TD[14], 0);
TextDrawSetSelectable(MainMenu_TD[14], true);

MainMenu_TD[15] = TextDrawCreate(295.0177, 103.9552, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[15], 26.0000, 27.0000);
TextDrawAlignment(MainMenu_TD[15], 1);
TextDrawColor(MainMenu_TD[15], 255);
TextDrawBackgroundColor(MainMenu_TD[15], 255);
TextDrawFont(MainMenu_TD[15], 4);
TextDrawSetProportional(MainMenu_TD[15], 0);
TextDrawSetShadow(MainMenu_TD[15], 0);
TextDrawSetSelectable(MainMenu_TD[15], true);

MainMenu_TD[16] = TextDrawCreate(266.0844, 133.2631, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[16], 26.0000, 27.0000);
TextDrawAlignment(MainMenu_TD[16], 1);
TextDrawColor(MainMenu_TD[16], 255);
TextDrawBackgroundColor(MainMenu_TD[16], 255);
TextDrawFont(MainMenu_TD[16], 4);
TextDrawSetProportional(MainMenu_TD[16], 0);
TextDrawSetShadow(MainMenu_TD[16], 0);
TextDrawSetSelectable(MainMenu_TD[16], true);

MainMenu_TD[17] = TextDrawCreate(295.1846, 133.5001, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[17], 26.0000, 27.0000);
TextDrawAlignment(MainMenu_TD[17], 1);
TextDrawColor(MainMenu_TD[17], 255);
TextDrawBackgroundColor(MainMenu_TD[17], 255);
TextDrawFont(MainMenu_TD[17], 4);
TextDrawSetProportional(MainMenu_TD[17], 0);
TextDrawSetShadow(MainMenu_TD[17], 0);
TextDrawSetSelectable(MainMenu_TD[17], true);

MainMenu_TD[18] = TextDrawCreate(266.0179, 162.9633, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[18], 26.0000, 27.0000);
TextDrawAlignment(MainMenu_TD[18], 1);
TextDrawColor(MainMenu_TD[18], 255);
TextDrawBackgroundColor(MainMenu_TD[18], 255);
TextDrawFont(MainMenu_TD[18], 4);
TextDrawSetProportional(MainMenu_TD[18], 0);
TextDrawSetShadow(MainMenu_TD[18], 0);
TextDrawSetSelectable(MainMenu_TD[18], true);

MainMenu_TD[19] = TextDrawCreate(295.3016, 162.8816, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[19], 26.0000, 27.0000);
TextDrawAlignment(MainMenu_TD[19], 1);
TextDrawColor(MainMenu_TD[19], 255);
TextDrawBackgroundColor(MainMenu_TD[19], 255);
TextDrawFont(MainMenu_TD[19], 4);
TextDrawSetProportional(MainMenu_TD[19], 0);
TextDrawSetShadow(MainMenu_TD[19], 0);
TextDrawSetSelectable(MainMenu_TD[19], true);

MainMenu_TD[20] = TextDrawCreate(332.6354, 100.6593, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[20], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[20], 1);
TextDrawColor(MainMenu_TD[20], 286331391);
TextDrawBackgroundColor(MainMenu_TD[20], 255);
TextDrawFont(MainMenu_TD[20], 4);
TextDrawSetProportional(MainMenu_TD[20], 0);
TextDrawSetShadow(MainMenu_TD[20], 0);
TextDrawSetSelectable(MainMenu_TD[20], true);

MainMenu_TD[21] = TextDrawCreate(363.2355, 100.5408, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[21], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[21], 1);
TextDrawColor(MainMenu_TD[21], 286331391);
TextDrawBackgroundColor(MainMenu_TD[21], 255);
TextDrawFont(MainMenu_TD[21], 4);
TextDrawSetProportional(MainMenu_TD[21], 0);
TextDrawSetShadow(MainMenu_TD[21], 0);
TextDrawSetSelectable(MainMenu_TD[21], true);

MainMenu_TD[22] = TextDrawCreate(393.7521, 100.5593, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[22], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[22], 1);
TextDrawColor(MainMenu_TD[22], 286331391);
TextDrawBackgroundColor(MainMenu_TD[22], 255);
TextDrawFont(MainMenu_TD[22], 4);
TextDrawSetProportional(MainMenu_TD[22], 0);
TextDrawSetShadow(MainMenu_TD[22], 0);
TextDrawSetSelectable(MainMenu_TD[22], true);

MainMenu_TD[23] = TextDrawCreate(424.3688, 100.5593, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[23], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[23], 1);
TextDrawColor(MainMenu_TD[23], 286331391);
TextDrawBackgroundColor(MainMenu_TD[23], 255);
TextDrawFont(MainMenu_TD[23], 4);
TextDrawSetProportional(MainMenu_TD[23], 0);
TextDrawSetShadow(MainMenu_TD[23], 0);
TextDrawSetSelectable(MainMenu_TD[23], true);

MainMenu_TD[24] = TextDrawCreate(455.1188, 100.5593, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[24], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[24], 1);
TextDrawColor(MainMenu_TD[24], 286331391);
TextDrawBackgroundColor(MainMenu_TD[24], 255);
TextDrawFont(MainMenu_TD[24], 4);
TextDrawSetProportional(MainMenu_TD[24], 0);
TextDrawSetShadow(MainMenu_TD[24], 0);
TextDrawSetSelectable(MainMenu_TD[24], true);

MainMenu_TD[25] = TextDrawCreate(332.6354, 132.4519, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[25], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[25], 1);
TextDrawColor(MainMenu_TD[25], 286331391);
TextDrawBackgroundColor(MainMenu_TD[25], 255);
TextDrawFont(MainMenu_TD[25], 4);
TextDrawSetProportional(MainMenu_TD[25], 0);
TextDrawSetShadow(MainMenu_TD[25], 0);
TextDrawSetSelectable(MainMenu_TD[25], true);

MainMenu_TD[26] = TextDrawCreate(363.2188, 132.4521, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[26], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[26], 1);
TextDrawColor(MainMenu_TD[26], 286331391);
TextDrawBackgroundColor(MainMenu_TD[26], 255);
TextDrawFont(MainMenu_TD[26], 4);
TextDrawSetProportional(MainMenu_TD[26], 0);
TextDrawSetShadow(MainMenu_TD[26], 0);
TextDrawSetSelectable(MainMenu_TD[26], true);

MainMenu_TD[27] = TextDrawCreate(393.8189, 132.5706, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[27], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[27], 1);
TextDrawColor(MainMenu_TD[27], 286331391);
TextDrawBackgroundColor(MainMenu_TD[27], 255);
TextDrawFont(MainMenu_TD[27], 4);
TextDrawSetProportional(MainMenu_TD[27], 0);
TextDrawSetShadow(MainMenu_TD[27], 0);
TextDrawSetSelectable(MainMenu_TD[27], true);

MainMenu_TD[28] = TextDrawCreate(424.5021, 132.6519, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[28], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[28], 1);
TextDrawColor(MainMenu_TD[28], 286331391);
TextDrawBackgroundColor(MainMenu_TD[28], 255);
TextDrawFont(MainMenu_TD[28], 4);
TextDrawSetProportional(MainMenu_TD[28], 0);
TextDrawSetShadow(MainMenu_TD[28], 0);
TextDrawSetSelectable(MainMenu_TD[28], true);

MainMenu_TD[29] = TextDrawCreate(455.2857, 132.6519, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[29], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[29], 1);
TextDrawColor(MainMenu_TD[29], 286331391);
TextDrawBackgroundColor(MainMenu_TD[29], 255);
TextDrawFont(MainMenu_TD[29], 4);
TextDrawSetProportional(MainMenu_TD[29], 0);
TextDrawSetShadow(MainMenu_TD[29], 0);
TextDrawSetSelectable(MainMenu_TD[29], true);

MainMenu_TD[30] = TextDrawCreate(332.3691, 164.5446, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[30], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[30], 1);
TextDrawColor(MainMenu_TD[30], 286331391);
TextDrawBackgroundColor(MainMenu_TD[30], 255);
TextDrawFont(MainMenu_TD[30], 4);
TextDrawSetProportional(MainMenu_TD[30], 0);
TextDrawSetShadow(MainMenu_TD[30], 0);
TextDrawSetSelectable(MainMenu_TD[30], true);

MainMenu_TD[31] = TextDrawCreate(363.3193, 164.5260, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[31], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[31], 1);
TextDrawColor(MainMenu_TD[31], 286331391);
TextDrawBackgroundColor(MainMenu_TD[31], 255);
TextDrawFont(MainMenu_TD[31], 4);
TextDrawSetProportional(MainMenu_TD[31], 0);
TextDrawSetShadow(MainMenu_TD[31], 0);
TextDrawSetSelectable(MainMenu_TD[31], true);

MainMenu_TD[32] = TextDrawCreate(393.8193, 164.4447, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[32], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[32], 1);
TextDrawColor(MainMenu_TD[32], 286331391);
TextDrawBackgroundColor(MainMenu_TD[32], 255);
TextDrawFont(MainMenu_TD[32], 4);
TextDrawSetProportional(MainMenu_TD[32], 0);
TextDrawSetShadow(MainMenu_TD[32], 0);
TextDrawSetSelectable(MainMenu_TD[32], true);

MainMenu_TD[33] = TextDrawCreate(424.5361, 164.4447, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[33], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[33], 1);
TextDrawColor(MainMenu_TD[33], 286331391);
TextDrawBackgroundColor(MainMenu_TD[33], 255);
TextDrawFont(MainMenu_TD[33], 4);
TextDrawSetProportional(MainMenu_TD[33], 0);
TextDrawSetShadow(MainMenu_TD[33], 0);
TextDrawSetSelectable(MainMenu_TD[33], true);

MainMenu_TD[34] = TextDrawCreate(455.2361, 164.4447, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[34], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[34], 1);
TextDrawColor(MainMenu_TD[34], 286331391);
TextDrawBackgroundColor(MainMenu_TD[34], 255);
TextDrawFont(MainMenu_TD[34], 4);
TextDrawSetProportional(MainMenu_TD[34], 0);
TextDrawSetShadow(MainMenu_TD[34], 0);
TextDrawSetSelectable(MainMenu_TD[34], true);

MainMenu_TD[35] = TextDrawCreate(332.4526, 196.4743, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[35], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[35], 1);
TextDrawColor(MainMenu_TD[35], 286331391);
TextDrawBackgroundColor(MainMenu_TD[35], 255);
TextDrawFont(MainMenu_TD[35], 4);
TextDrawSetProportional(MainMenu_TD[35], 0);
TextDrawSetShadow(MainMenu_TD[35], 0);
TextDrawSetSelectable(MainMenu_TD[35], true);

MainMenu_TD[36] = TextDrawCreate(363.1527, 196.4743, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[36], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[36], 1);
TextDrawColor(MainMenu_TD[36], 286331391);
TextDrawBackgroundColor(MainMenu_TD[36], 255);
TextDrawFont(MainMenu_TD[36], 4);
TextDrawSetProportional(MainMenu_TD[36], 0);
TextDrawSetShadow(MainMenu_TD[36], 0);
TextDrawSetSelectable(MainMenu_TD[36], true);

MainMenu_TD[37] = TextDrawCreate(393.6694, 196.5926, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[37], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[37], 1);
TextDrawColor(MainMenu_TD[37], 286331391);
TextDrawBackgroundColor(MainMenu_TD[37], 255);
TextDrawFont(MainMenu_TD[37], 4);
TextDrawSetProportional(MainMenu_TD[37], 0);
TextDrawSetShadow(MainMenu_TD[37], 0);
TextDrawSetSelectable(MainMenu_TD[37], true);

MainMenu_TD[38] = TextDrawCreate(424.3861, 196.5926, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[38], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[38], 1);
TextDrawColor(MainMenu_TD[38], 286331391);
TextDrawBackgroundColor(MainMenu_TD[38], 255);
TextDrawFont(MainMenu_TD[38], 4);
TextDrawSetProportional(MainMenu_TD[38], 0);
TextDrawSetShadow(MainMenu_TD[38], 0);
TextDrawSetSelectable(MainMenu_TD[38], true);

MainMenu_TD[39] = TextDrawCreate(455.2195, 196.5926, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[39], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[39], 1);
TextDrawColor(MainMenu_TD[39], 286331391);
TextDrawBackgroundColor(MainMenu_TD[39], 255);
TextDrawFont(MainMenu_TD[39], 4);
TextDrawSetProportional(MainMenu_TD[39], 0);
TextDrawSetShadow(MainMenu_TD[39], 0);
TextDrawSetSelectable(MainMenu_TD[39], true);

MainMenu_TD[40] = TextDrawCreate(332.4194, 228.2039, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[40], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[40], 1);
TextDrawColor(MainMenu_TD[40], 286331391);
TextDrawBackgroundColor(MainMenu_TD[40], 255);
TextDrawFont(MainMenu_TD[40], 4);
TextDrawSetProportional(MainMenu_TD[40], 0);
TextDrawSetShadow(MainMenu_TD[40], 0);
TextDrawSetSelectable(MainMenu_TD[40], true);

MainMenu_TD[41] = TextDrawCreate(363.1361, 228.2039, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[41], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[41], 1);
TextDrawColor(MainMenu_TD[41], 286331391);
TextDrawBackgroundColor(MainMenu_TD[41], 255);
TextDrawFont(MainMenu_TD[41], 4);
TextDrawSetProportional(MainMenu_TD[41], 0);
TextDrawSetShadow(MainMenu_TD[41], 0);
TextDrawSetSelectable(MainMenu_TD[41], true);

MainMenu_TD[42] = TextDrawCreate(393.7195, 228.2037, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[42], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[42], 1);
TextDrawColor(MainMenu_TD[42], 286331391);
TextDrawBackgroundColor(MainMenu_TD[42], 255);
TextDrawFont(MainMenu_TD[42], 4);
TextDrawSetProportional(MainMenu_TD[42], 0);
TextDrawSetShadow(MainMenu_TD[42], 0);
TextDrawSetSelectable(MainMenu_TD[42], true);

MainMenu_TD[43] = TextDrawCreate(424.4194, 228.2037, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[43], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[43], 1);
TextDrawColor(MainMenu_TD[43], 286331391);
TextDrawBackgroundColor(MainMenu_TD[43], 255);
TextDrawFont(MainMenu_TD[43], 4);
TextDrawSetProportional(MainMenu_TD[43], 0);
TextDrawSetShadow(MainMenu_TD[43], 0);
TextDrawSetSelectable(MainMenu_TD[43], true);

MainMenu_TD[44] = TextDrawCreate(455.1195, 228.2039, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[44], 30.0000, 31.0000);
TextDrawAlignment(MainMenu_TD[44], 1);
TextDrawColor(MainMenu_TD[44], 286331391);
TextDrawBackgroundColor(MainMenu_TD[44], 255);
TextDrawFont(MainMenu_TD[44], 4);
TextDrawSetProportional(MainMenu_TD[44], 0);
TextDrawSetShadow(MainMenu_TD[44], 0);
TextDrawSetSelectable(MainMenu_TD[44], true);

MainMenu_TD[45] = TextDrawCreate(231.6665, 195.1851, "Box"); // ?????
TextDrawLetterSize(MainMenu_TD[45], 0.0000, 0.3332);
TextDrawTextSize(MainMenu_TD[45], 323.0000, 0.0000);
TextDrawAlignment(MainMenu_TD[45], 1);
TextDrawColor(MainMenu_TD[45], -1);
TextDrawUseBox(MainMenu_TD[45], 1);
TextDrawBoxColor(MainMenu_TD[45], 255);
TextDrawBackgroundColor(MainMenu_TD[45], 255);
TextDrawFont(MainMenu_TD[45], 1);
TextDrawSetProportional(MainMenu_TD[45], 1);
TextDrawSetShadow(MainMenu_TD[45], 0);

MainMenu_TD[46] = TextDrawCreate(246.2500, 202.1851, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[46], 75.0000, 4.0000);
TextDrawAlignment(MainMenu_TD[46], 1);
TextDrawColor(MainMenu_TD[46], 255);
TextDrawBackgroundColor(MainMenu_TD[46], 255);
TextDrawFont(MainMenu_TD[46], 4);
TextDrawSetProportional(MainMenu_TD[46], 0);
TextDrawSetShadow(MainMenu_TD[46], 0);

MainMenu_TD[47] = TextDrawCreate(246.2500, 209.2855, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[47], 75.0000, 4.0000);
TextDrawAlignment(MainMenu_TD[47], 1);
TextDrawColor(MainMenu_TD[47], 255);
TextDrawBackgroundColor(MainMenu_TD[47], 255);
TextDrawFont(MainMenu_TD[47], 4);
TextDrawSetProportional(MainMenu_TD[47], 0);
TextDrawSetShadow(MainMenu_TD[47], 0);

MainMenu_TD[48] = TextDrawCreate(246.2500, 216.2859, "LD_SPAC:white"); // ?????
TextDrawTextSize(MainMenu_TD[48], 75.0000, 4.0000);
TextDrawAlignment(MainMenu_TD[48], 1);
TextDrawColor(MainMenu_TD[48], 255);
TextDrawBackgroundColor(MainMenu_TD[48], 255);
TextDrawFont(MainMenu_TD[48], 4);
TextDrawSetProportional(MainMenu_TD[48], 0);
TextDrawSetShadow(MainMenu_TD[48], 0);

MainMenu_TD[49] = TextDrawCreate(238.1999, 201.5074, "Health"); // ?????
TextDrawLetterSize(MainMenu_TD[49], 0.0925, 0.5472);
TextDrawAlignment(MainMenu_TD[49], 2);
TextDrawColor(MainMenu_TD[49], -1);
TextDrawBackgroundColor(MainMenu_TD[49], 255);
TextDrawFont(MainMenu_TD[49], 2);
TextDrawSetProportional(MainMenu_TD[49], 1);
TextDrawSetShadow(MainMenu_TD[49], 0);

MainMenu_TD[50] = TextDrawCreate(238.3000, 208.5666, "ARMOUR"); // ?????
TextDrawLetterSize(MainMenu_TD[50], 0.0925, 0.5472);
TextDrawAlignment(MainMenu_TD[50], 2);
TextDrawColor(MainMenu_TD[50], -1);
TextDrawBackgroundColor(MainMenu_TD[50], 255);
TextDrawFont(MainMenu_TD[50], 2);
TextDrawSetProportional(MainMenu_TD[50], 1);
TextDrawSetShadow(MainMenu_TD[50], 0);

MainMenu_TD[51] = TextDrawCreate(238.3000, 215.5075, "Satiety"); // ?????
TextDrawLetterSize(MainMenu_TD[51], 0.0925, 0.5472);
TextDrawAlignment(MainMenu_TD[51], 2);
TextDrawColor(MainMenu_TD[51], -1);
TextDrawBackgroundColor(MainMenu_TD[51], 255);
TextDrawFont(MainMenu_TD[51], 2);
TextDrawSetProportional(MainMenu_TD[51], 1);
TextDrawSetShadow(MainMenu_TD[51], 0);
