	Roulette_TD[0] = TextDrawCreate(275.9443, 172.4998, "Box"); // ?????
	TextDrawLetterSize(Roulette_TD[0], 0.0000, 20.6354);
	TextDrawTextSize(Roulette_TD[0], 390.9007, 0.0000);
	TextDrawAlignment(Roulette_TD[0], 1);
	TextDrawColor(Roulette_TD[0], -1);
	TextDrawUseBox(Roulette_TD[0], 1);
	TextDrawBoxColor(Roulette_TD[0], 0x74BB88AA);
	TextDrawBackgroundColor(Roulette_TD[0], 255);
	TextDrawFont(Roulette_TD[0], 1);
	TextDrawSetProportional(Roulette_TD[0], 1);
	TextDrawSetShadow(Roulette_TD[0], 0);

	Roulette_TD[1] = TextDrawCreate(314.5632, 332.7166, "Genuine"); // ?????
	TextDrawLetterSize(Roulette_TD[1], 0.4000, 1.6000);
	TextDrawAlignment(Roulette_TD[1], 1);
	TextDrawColor(Roulette_TD[1], 0xFFFFFFAA);
	TextDrawBackgroundColor(Roulette_TD[1], 255);
	TextDrawFont(Roulette_TD[1], 0);
	TextDrawSetProportional(Roulette_TD[1], 1);
	TextDrawSetShadow(Roulette_TD[1], 0);

	Roulette_TD[2] = TextDrawCreate(309.9834, 344.9664, "Role_Play"); // ?????
	TextDrawLetterSize(Roulette_TD[2], 0.3817, 1.3782);
	TextDrawAlignment(Roulette_TD[2], 1);
	TextDrawColor(Roulette_TD[2], 0xFFFFFFAA);
	TextDrawBackgroundColor(Roulette_TD[2], 255);
	TextDrawFont(Roulette_TD[2], 0);
	TextDrawSetProportional(Roulette_TD[2], 1);
	TextDrawSetShadow(Roulette_TD[2], 0);

	Roulette_TD[3] = TextDrawCreate(324.5022, 362.0833, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(Roulette_TD[3], 19.0000, 22.0000);
	TextDrawAlignment(Roulette_TD[3], 1);
	TextDrawColor(Roulette_TD[3], 5603583);
	TextDrawBackgroundColor(Roulette_TD[3], 255);
	TextDrawFont(Roulette_TD[3], 4);
	TextDrawSetProportional(Roulette_TD[3], 0);
	TextDrawSetShadow(Roulette_TD[3], 0);
	TextDrawSetSelectable(Roulette_TD[3], true);

	Roulette_TD[4] = TextDrawCreate(330.1242, 367.0667, "X"); // ?????
	TextDrawLetterSize(Roulette_TD[4], 0.4341, 1.2323);
	TextDrawAlignment(Roulette_TD[4], 1);
	TextDrawColor(Roulette_TD[4], -1);
	TextDrawBackgroundColor(Roulette_TD[4], 255);
	TextDrawFont(Roulette_TD[4], 3);
	TextDrawSetProportional(Roulette_TD[4], 1);
	TextDrawSetShadow(Roulette_TD[4], 0);

	Roulette_TD[5] = TextDrawCreate(317.4744, 216.2500, "LD_SPAC:white"); // ?????
	TextDrawTextSize(Roulette_TD[5], 32.0000, 7.2199);
	TextDrawAlignment(Roulette_TD[5], 1);
	TextDrawColor(Roulette_TD[5], 0x74BB88AA);
	TextDrawBackgroundColor(Roulette_TD[5], 255);
	TextDrawFont(Roulette_TD[5], 4);
	TextDrawSetProportional(Roulette_TD[5], 0);
	TextDrawSetShadow(Roulette_TD[5], 0);
	TextDrawSetSelectable(Roulette_TD[5], true);

	Roulette_TD[6] = TextDrawCreate(318.9484, 214.7165, "BRONZE"); // ?????
	TextDrawLetterSize(Roulette_TD[6], 0.1840, 0.9757);
	TextDrawAlignment(Roulette_TD[6], 1);
	TextDrawColor(Roulette_TD[6], 0xEC674AAA);
	TextDrawBackgroundColor(Roulette_TD[6], 255);
	TextDrawFont(Roulette_TD[6], 2);
	TextDrawSetProportional(Roulette_TD[6], 1);
	TextDrawSetShadow(Roulette_TD[6], 0);

	Roulette_TD[7] = TextDrawCreate(317.4744, 224.8504, "LD_SPAC:white"); // ?????
	TextDrawTextSize(Roulette_TD[7], 32.0000, 7.2199);
	TextDrawAlignment(Roulette_TD[7], 1);
	TextDrawColor(Roulette_TD[7], 0x74BB88AA);
	TextDrawBackgroundColor(Roulette_TD[7], 255);
	TextDrawFont(Roulette_TD[7], 4);
	TextDrawSetProportional(Roulette_TD[7], 0);
	TextDrawSetShadow(Roulette_TD[7], 0);
	TextDrawSetSelectable(Roulette_TD[7], true);

	Roulette_TD[8] = TextDrawCreate(317.2430, 232.9510, "LD_SPAC:white"); // ?????
	TextDrawTextSize(Roulette_TD[8], 32.0000, 7.2199);
	TextDrawAlignment(Roulette_TD[8], 1);
	TextDrawColor(Roulette_TD[8], 0x74BB88AA);
	TextDrawBackgroundColor(Roulette_TD[8], 255);
	TextDrawFont(Roulette_TD[8], 4);
	TextDrawSetProportional(Roulette_TD[8], 0);
	TextDrawSetShadow(Roulette_TD[8], 0);
	TextDrawSetSelectable(Roulette_TD[8], true);

	Roulette_TD[9] = TextDrawCreate(333.0728, 223.1833, "SILVER"); // ?????
	TextDrawLetterSize(Roulette_TD[9], 0.1840, 0.9757);
	TextDrawAlignment(Roulette_TD[9], 2);
	TextDrawColor(Roulette_TD[9], -1);
	TextDrawBackgroundColor(Roulette_TD[9], 255);
	TextDrawFont(Roulette_TD[9], 2);
	TextDrawSetProportional(Roulette_TD[9], 1);
	TextDrawSetShadow(Roulette_TD[9], 0);

	Roulette_TD[10] = TextDrawCreate(332.8356, 231.6999, "GOLD"); // ?????
	TextDrawLetterSize(Roulette_TD[10], 0.1840, 0.9757);
	TextDrawAlignment(Roulette_TD[10], 2);
	TextDrawColor(Roulette_TD[10], -65281);
	TextDrawBackgroundColor(Roulette_TD[10], 255);
	TextDrawFont(Roulette_TD[10], 2);
	TextDrawSetProportional(Roulette_TD[10], 1);
	TextDrawSetShadow(Roulette_TD[10], 0);

	Roulette_TD[11] = TextDrawCreate(316.1741, 246.3166, "COINS:"); // ?????
	TextDrawLetterSize(Roulette_TD[11], 0.2116, 0.9408);
	TextDrawAlignment(Roulette_TD[11], 1);
	TextDrawColor(Roulette_TD[11], 0xFC3131AA);
	TextDrawBackgroundColor(Roulette_TD[11], 255);
	TextDrawFont(Roulette_TD[11], 3);
	TextDrawSetProportional(Roulette_TD[11], 1);
	TextDrawSetShadow(Roulette_TD[11], 0);

	Roulette_TD[12] = TextDrawCreate(321.4541, 262.7166, "LD_NONE:shpnorm"); // ?????
	TextDrawTextSize(Roulette_TD[12], 24.0000, 22.0000);
	TextDrawAlignment(Roulette_TD[12], 1);
	TextDrawColor(Roulette_TD[12], -1);
	TextDrawBackgroundColor(Roulette_TD[12], 255);
	TextDrawFont(Roulette_TD[12], 4);
	TextDrawSetProportional(Roulette_TD[12], 0);
	TextDrawSetShadow(Roulette_TD[12], 0);
	TextDrawSetSelectable(Roulette_TD[12], true);
