Satiety_TD[0] = TextDrawCreate(28.9988, 226.3477, "ld_beat:chit"); // ionoi
TextDrawTextSize(Satiety_TD[0], 9.0000, 10.0000);
TextDrawAlignment(Satiety_TD[0], 1);
TextDrawColor(Satiety_TD[0], 522133503);
TextDrawBackgroundColor(Satiety_TD[0], 255);
TextDrawFont(Satiety_TD[0], 4);
TextDrawSetProportional(Satiety_TD[0], 0);
TextDrawSetShadow(Satiety_TD[0], 0);

Satiety_TD[1] = TextDrawCreate(28.9988, 253.3103, "ld_beat:chit"); // ionoi
TextDrawTextSize(Satiety_TD[1], 9.0000, 10.0000);
TextDrawAlignment(Satiety_TD[1], 1);
TextDrawColor(Satiety_TD[1], 522133503);
TextDrawBackgroundColor(Satiety_TD[1], 255);
TextDrawFont(Satiety_TD[1], 4);
TextDrawSetProportional(Satiety_TD[1], 0);
TextDrawSetShadow(Satiety_TD[1], 0);

Satiety_TD[2] = TextDrawCreate(136.6657, 226.3477, "ld_beat:chit"); // ionoi
TextDrawTextSize(Satiety_TD[2], 9.0000, 10.0000);
TextDrawAlignment(Satiety_TD[2], 1);
TextDrawColor(Satiety_TD[2], 522133503);
TextDrawBackgroundColor(Satiety_TD[2], 255);
TextDrawFont(Satiety_TD[2], 4);
TextDrawSetProportional(Satiety_TD[2], 0);
TextDrawSetShadow(Satiety_TD[2], 0);

Satiety_TD[3] = TextDrawCreate(136.6657, 253.3103, "ld_beat:chit"); // ionoi
TextDrawTextSize(Satiety_TD[3], 9.0000, 10.0000);
TextDrawAlignment(Satiety_TD[3], 1);
TextDrawColor(Satiety_TD[3], 522133503);
TextDrawBackgroundColor(Satiety_TD[3], 255);
TextDrawFont(Satiety_TD[3], 4);
TextDrawSetProportional(Satiety_TD[3], 0);
TextDrawSetShadow(Satiety_TD[3], 0);

Satiety_TD[4] = TextDrawCreate(33.9992, 227.6925, "LD_SPAC:white"); // ionoi
TextDrawTextSize(Satiety_TD[4], 107.0000, 34.0000);
TextDrawAlignment(Satiety_TD[4], 1);
TextDrawColor(Satiety_TD[4], 522133503);
TextDrawBackgroundColor(Satiety_TD[4], 255);
TextDrawFont(Satiety_TD[4], 4);
TextDrawSetProportional(Satiety_TD[4], 0);
TextDrawSetShadow(Satiety_TD[4], 0);

Satiety_TD[5] = TextDrawCreate(30.3324, 231.4257, "LD_SPAC:white"); // ionoi
TextDrawTextSize(Satiety_TD[5], 114.0000, 26.0000);
TextDrawAlignment(Satiety_TD[5], 1);
TextDrawColor(Satiety_TD[5], 522133503);
TextDrawBackgroundColor(Satiety_TD[5], 255);
TextDrawFont(Satiety_TD[5], 4);
TextDrawSetProportional(Satiety_TD[5], 0);
TextDrawSetShadow(Satiety_TD[5], 0);

Satiety_TD[6] = TextDrawCreate(30.3323, 227.6925, "particle:lamp_shad_64"); // ionoi
TextDrawTextSize(Satiety_TD[6], 113.0000, 34.0000);
TextDrawAlignment(Satiety_TD[6], 1);
TextDrawColor(Satiety_TD[6], 1280068728);
TextDrawBackgroundColor(Satiety_TD[6], 255);
TextDrawFont(Satiety_TD[6], 4);
TextDrawSetProportional(Satiety_TD[6], 0);
TextDrawSetShadow(Satiety_TD[6], 0);

Satiety_TD[7] = TextDrawCreate(33.9996, 221.1110, "O"); // ionoi
TextDrawLetterSize(Satiety_TD[7], 0.8366, 4.6529);
TextDrawAlignment(Satiety_TD[7], 1);
TextDrawColor(Satiety_TD[7], 977690367);
TextDrawBackgroundColor(Satiety_TD[7], 255);
TextDrawFont(Satiety_TD[7], 2);
TextDrawSetProportional(Satiety_TD[7], 1);
TextDrawSetShadow(Satiety_TD[7], 0);

Satiety_TD[8] = TextDrawCreate(33.9996, 151.4223, "."); // ionoi
TextDrawLetterSize(Satiety_TD[8], 2.2411, 13.1898);
TextDrawAlignment(Satiety_TD[8], 1);
TextDrawColor(Satiety_TD[8], 1112566783);
TextDrawBackgroundColor(Satiety_TD[8], 255);
TextDrawFont(Satiety_TD[8], 3);
TextDrawSetProportional(Satiety_TD[8], 1);
TextDrawSetShadow(Satiety_TD[8], 0);

Satiety_TD[9] = TextDrawCreate(39.3331, 237.7044, "!"); // ionoi
TextDrawLetterSize(Satiety_TD[9], 0.4000, 1.6000);
TextDrawTextSize(Satiety_TD[9], 0.0000, -3.0000);
TextDrawAlignment(Satiety_TD[9], 2);
TextDrawColor(Satiety_TD[9], 1870104831);
TextDrawBackgroundColor(Satiety_TD[9], 255);
TextDrawFont(Satiety_TD[9], 1);
TextDrawSetProportional(Satiety_TD[9], 1);
TextDrawSetShadow(Satiety_TD[9], 0);

Satiety_TD[10] = TextDrawCreate(41.9997, 240.1929, "INFO"); // ionoi
TextDrawLetterSize(Satiety_TD[10], 0.1419, 0.6915);
TextDrawTextSize(Satiety_TD[10], -3.0000, 0.0000);
TextDrawAlignment(Satiety_TD[10], 1);
TextDrawColor(Satiety_TD[10], 1870104831);
TextDrawBackgroundColor(Satiety_TD[10], 255);
TextDrawFont(Satiety_TD[10], 1);
TextDrawSetProportional(Satiety_TD[10], 1);
TextDrawSetShadow(Satiety_TD[10], 0);

Satiety_TD[11] = TextDrawCreate(59.9997, 249.9920, "LD_SPAC:white"); // ionoi
TextDrawTextSize(Satiety_TD[11], 78.0000, 5.0000);
TextDrawAlignment(Satiety_TD[11], 1);
TextDrawColor(Satiety_TD[11], 774778623);
TextDrawBackgroundColor(Satiety_TD[11], 255);
TextDrawFont(Satiety_TD[11], 4);
TextDrawSetProportional(Satiety_TD[11], 0);
TextDrawSetShadow(Satiety_TD[11], 0);

Satiety_TD[12] = TextDrawCreate(72.3329, 239.7776, "SATIETY"); // ionoi
TextDrawLetterSize(Satiety_TD[12], 0.1972, 0.9236);
TextDrawAlignment(Satiety_TD[12], 2);
TextDrawColor(Satiety_TD[12], -1061109505);
TextDrawBackgroundColor(Satiety_TD[12], 255);
TextDrawFont(Satiety_TD[12], 1);
TextDrawSetProportional(Satiety_TD[12], 1);
TextDrawSetShadow(Satiety_TD[12], 0);

Satiety_TD[13] = TextDrawCreate(41.9997, 244.7559, "BOX"); // ionoi
TextDrawLetterSize(Satiety_TD[13], 0.1419, 0.6915);
TextDrawTextSize(Satiety_TD[13], -3.0000, 0.0000);
TextDrawAlignment(Satiety_TD[13], 1);
TextDrawColor(Satiety_TD[13], 1870104831);
TextDrawBackgroundColor(Satiety_TD[13], 255);
TextDrawFont(Satiety_TD[13], 1);
TextDrawSetProportional(Satiety_TD[13], 1);
TextDrawSetShadow(Satiety_TD[13], 0);