spawnchoose_TD[0] = TextDrawCreate(229.8000, 197.8087, "LD_SPAC:white"); // пусто
TextDrawTextSize(spawnchoose_TD[0], 175.0000, 31.0000);
TextDrawAlignment(spawnchoose_TD[0], 1);
TextDrawColor(spawnchoose_TD[0], 522133503);
TextDrawBackgroundColor(spawnchoose_TD[0], 255);
TextDrawFont(spawnchoose_TD[0], 4);
TextDrawSetProportional(spawnchoose_TD[0], 0);
TextDrawSetShadow(spawnchoose_TD[0], 0);

spawnchoose_TD[1] = TextDrawCreate(217.4001, 193.2220, "LD_BEAT:chit"); // пусто
TextDrawTextSize(spawnchoose_TD[1], 24.0000, 28.0000);
TextDrawAlignment(spawnchoose_TD[1], 1);
TextDrawColor(spawnchoose_TD[1], 522133503);
TextDrawBackgroundColor(spawnchoose_TD[1], 255);
TextDrawFont(spawnchoose_TD[1], 4);
TextDrawSetProportional(spawnchoose_TD[1], 0);
TextDrawSetShadow(spawnchoose_TD[1], 0);

spawnchoose_TD[2] = TextDrawCreate(393.7008, 193.2220, "LD_BEAT:chit"); // пусто
TextDrawTextSize(spawnchoose_TD[2], 24.0000, 28.0000);
TextDrawAlignment(spawnchoose_TD[2], 1);
TextDrawColor(spawnchoose_TD[2], 522133503);
TextDrawBackgroundColor(spawnchoose_TD[2], 255);
TextDrawFont(spawnchoose_TD[2], 4);
TextDrawSetProportional(spawnchoose_TD[2], 0);
TextDrawSetShadow(spawnchoose_TD[2], 0);

spawnchoose_TD[3] = TextDrawCreate(221.5000, 209.2576, "LD_SPAC:white"); // пусто
TextDrawTextSize(spawnchoose_TD[3], 192.0000, 66.0000);
TextDrawAlignment(spawnchoose_TD[3], 1);
TextDrawColor(spawnchoose_TD[3], 522133503);
TextDrawBackgroundColor(spawnchoose_TD[3], 255);
TextDrawFont(spawnchoose_TD[3], 4);
TextDrawSetProportional(spawnchoose_TD[3], 0);
TextDrawSetShadow(spawnchoose_TD[3], 0);

spawnchoose_TD[4] = TextDrawCreate(288.1999, 187.8532, "LD_SPAC:white"); // пусто
TextDrawTextSize(spawnchoose_TD[4], 56.0000, 19.0000);
TextDrawAlignment(spawnchoose_TD[4], 1);
TextDrawColor(spawnchoose_TD[4], -1523963137);
TextDrawBackgroundColor(spawnchoose_TD[4], 255);
TextDrawFont(spawnchoose_TD[4], 4);
TextDrawSetProportional(spawnchoose_TD[4], 0);
TextDrawSetShadow(spawnchoose_TD[4], 0);

spawnchoose_TD[5] = TextDrawCreate(278.3999, 183.3822, "LD_BEAT:chit"); // пусто
TextDrawTextSize(spawnchoose_TD[5], 18.0000, 28.0000);
TextDrawAlignment(spawnchoose_TD[5], 1);
TextDrawColor(spawnchoose_TD[5], -1523963137);
TextDrawBackgroundColor(spawnchoose_TD[5], 255);
TextDrawFont(spawnchoose_TD[5], 4);
TextDrawSetProportional(spawnchoose_TD[5], 0);
TextDrawSetShadow(spawnchoose_TD[5], 0);

spawnchoose_TD[6] = TextDrawCreate(334.2998, 183.3845, "LD_BEAT:chit"); // пусто
TextDrawTextSize(spawnchoose_TD[6], 18.0000, 28.0000);
TextDrawAlignment(spawnchoose_TD[6], 1);
TextDrawColor(spawnchoose_TD[6], -1523963137);
TextDrawBackgroundColor(spawnchoose_TD[6], 255);
TextDrawFont(spawnchoose_TD[6], 4);
TextDrawSetProportional(spawnchoose_TD[6], 0);
TextDrawSetShadow(spawnchoose_TD[6], 0);

spawnchoose_TD[7] = TextDrawCreate(313.9999, 191.9910, "SELECT_SPAWN"); // пусто
TextDrawLetterSize(spawnchoose_TD[7], 0.1951, 1.2664);
TextDrawAlignment(spawnchoose_TD[7], 2);
TextDrawColor(spawnchoose_TD[7], -1);
TextDrawBackgroundColor(spawnchoose_TD[7], 255);
TextDrawFont(spawnchoose_TD[7], 1);
TextDrawSetProportional(spawnchoose_TD[7], 1);
TextDrawSetShadow(spawnchoose_TD[7], 0);

spawnchoose_TD[8] = TextDrawCreate(225.8000, 212.2444, ""); // пусто
TextDrawTextSize(spawnchoose_TD[8], 45.0000, 55.0000);
TextDrawAlignment(spawnchoose_TD[8], 1);
TextDrawColor(spawnchoose_TD[8], -1);
TextDrawBackgroundColor(spawnchoose_TD[8], 252645375);
TextDrawFont(spawnchoose_TD[8], 5);
TextDrawSetProportional(spawnchoose_TD[8], 0);
TextDrawSetShadow(spawnchoose_TD[8], 0);
TextDrawSetSelectable(spawnchoose_TD[8], true);
TextDrawSetPreviewModel(spawnchoose_TD[8], 1239);
TextDrawSetPreviewRot(spawnchoose_TD[8], 0.0000, 0.0000, 180.0000, 1.0000);

spawnchoose_TD[9] = TextDrawCreate(271.4000, 212.2444, ""); // пусто
TextDrawTextSize(spawnchoose_TD[9], 45.0000, 55.0000);
TextDrawAlignment(spawnchoose_TD[9], 1);
TextDrawColor(spawnchoose_TD[9], -1);
TextDrawBackgroundColor(spawnchoose_TD[9], 252645375);
TextDrawFont(spawnchoose_TD[9], 5);
TextDrawSetProportional(spawnchoose_TD[9], 0);
TextDrawSetShadow(spawnchoose_TD[9], 0);
TextDrawSetSelectable(spawnchoose_TD[9], true);
TextDrawSetPreviewModel(spawnchoose_TD[9], 19524);
TextDrawSetPreviewRot(spawnchoose_TD[9], 0.0000, 0.0000, 0.6000, 0.6499);

spawnchoose_TD[10] = TextDrawCreate(318.2000, 212.2444, ""); // пусто
TextDrawTextSize(spawnchoose_TD[10], 45.0000, 55.0000);
TextDrawAlignment(spawnchoose_TD[10], 1);
TextDrawColor(spawnchoose_TD[10], -1);
TextDrawBackgroundColor(spawnchoose_TD[10], 252645375);
TextDrawFont(spawnchoose_TD[10], 5);
TextDrawSetProportional(spawnchoose_TD[10], 0);
TextDrawSetShadow(spawnchoose_TD[10], 0);
TextDrawSetSelectable(spawnchoose_TD[10], true);
TextDrawSetPreviewModel(spawnchoose_TD[10], 1274);
TextDrawSetPreviewRot(spawnchoose_TD[10], 0.0000, 0.0000, 180.0000, 1.0000);

spawnchoose_TD[11] = TextDrawCreate(364.2000, 212.2421, ""); // пусто
TextDrawTextSize(spawnchoose_TD[11], 45.0000, 55.0000);
TextDrawAlignment(spawnchoose_TD[11], 1);
TextDrawColor(spawnchoose_TD[11], -1);
TextDrawBackgroundColor(spawnchoose_TD[11], 252645375);
TextDrawFont(spawnchoose_TD[11], 5);
TextDrawSetProportional(spawnchoose_TD[11], 0);
TextDrawSetShadow(spawnchoose_TD[11], 0);
TextDrawSetSelectable(spawnchoose_TD[11], true);
TextDrawSetPreviewModel(spawnchoose_TD[11], 19197);
TextDrawSetPreviewRot(spawnchoose_TD[11], 0.0000, 0.0000, 0.0000, 1.0000);

spawnchoose_TD[12] = TextDrawCreate(228.2001, 278.5621, "LD_SPAC:white"); // пусто
TextDrawTextSize(spawnchoose_TD[12], 181.0000, 16.0000);
TextDrawAlignment(spawnchoose_TD[12], 1);
TextDrawColor(spawnchoose_TD[12], 522133503);
TextDrawBackgroundColor(spawnchoose_TD[12], 255);
TextDrawFont(spawnchoose_TD[12], 4);
TextDrawSetProportional(spawnchoose_TD[12], 0);
TextDrawSetShadow(spawnchoose_TD[12], 0);

spawnchoose_TD[13] = TextDrawCreate(218.7001, 274.5452, "LD_BEAT:chit"); // пусто
TextDrawTextSize(spawnchoose_TD[13], 18.0000, 24.0000);
TextDrawAlignment(spawnchoose_TD[13], 1);
TextDrawColor(spawnchoose_TD[13], 522133503);
TextDrawBackgroundColor(spawnchoose_TD[13], 255);
TextDrawFont(spawnchoose_TD[13], 4);
TextDrawSetProportional(spawnchoose_TD[13], 0);
TextDrawSetShadow(spawnchoose_TD[13], 0);

spawnchoose_TD[14] = TextDrawCreate(398.8001, 274.5768, "LD_BEAT:chit"); // пусто
TextDrawTextSize(spawnchoose_TD[14], 18.0000, 24.0000);
TextDrawAlignment(spawnchoose_TD[14], 1);
TextDrawColor(spawnchoose_TD[14], 522133503);
TextDrawBackgroundColor(spawnchoose_TD[14], 255);
TextDrawFont(spawnchoose_TD[14], 4);
TextDrawSetProportional(spawnchoose_TD[14], 0);
TextDrawSetShadow(spawnchoose_TD[14], 0);

spawnchoose_TD[15] = TextDrawCreate(248.0000, 281.7450, "SPAWN"); // пусто
TextDrawLetterSize(spawnchoose_TD[15], 0.1888, 1.0275);
TextDrawTextSize(spawnchoose_TD[15], 0.0000, 41.0000);
TextDrawAlignment(spawnchoose_TD[15], 2);
TextDrawColor(spawnchoose_TD[15], -1);
TextDrawUseBox(spawnchoose_TD[15], 1);
TextDrawBoxColor(spawnchoose_TD[15], 252645375);
TextDrawBackgroundColor(spawnchoose_TD[15], 255);
TextDrawFont(spawnchoose_TD[15], 1);
TextDrawSetProportional(spawnchoose_TD[15], 1);
TextDrawSetShadow(spawnchoose_TD[15], 0);

spawnchoose_TD[16] = TextDrawCreate(293.5999, 281.9037, "HOUSE"); // пусто
TextDrawLetterSize(spawnchoose_TD[16], 0.1888, 1.0275);
TextDrawTextSize(spawnchoose_TD[16], 0.0000, 41.0000);
TextDrawAlignment(spawnchoose_TD[16], 2);
TextDrawColor(spawnchoose_TD[16], -1);
TextDrawUseBox(spawnchoose_TD[16], 1);
TextDrawBoxColor(spawnchoose_TD[16], 252645375);
TextDrawBackgroundColor(spawnchoose_TD[16], 255);
TextDrawFont(spawnchoose_TD[16], 1);
TextDrawSetProportional(spawnchoose_TD[16], 1);
TextDrawSetShadow(spawnchoose_TD[16], 0);

spawnchoose_TD[17] = TextDrawCreate(340.5999, 281.7690, "FRACTION"); // пусто
TextDrawLetterSize(spawnchoose_TD[17], 0.1888, 1.0275);
TextDrawTextSize(spawnchoose_TD[17], 0.0000, 41.0000);
TextDrawAlignment(spawnchoose_TD[17], 2);
TextDrawColor(spawnchoose_TD[17], -1);
TextDrawUseBox(spawnchoose_TD[17], 1);
TextDrawBoxColor(spawnchoose_TD[17], 252645375);
TextDrawBackgroundColor(spawnchoose_TD[17], 255);
TextDrawFont(spawnchoose_TD[17], 1);
TextDrawSetProportional(spawnchoose_TD[17], 1);
TextDrawSetShadow(spawnchoose_TD[17], 0);

spawnchoose_TD[18] = TextDrawCreate(386.4999, 281.9231, "EXIT_POINT"); // пусто
TextDrawLetterSize(spawnchoose_TD[18], 0.1888, 1.0275);
TextDrawTextSize(spawnchoose_TD[18], 0.0000, 41.0000);
TextDrawAlignment(spawnchoose_TD[18], 2);
TextDrawColor(spawnchoose_TD[18], -1);
TextDrawUseBox(spawnchoose_TD[18], 1);
TextDrawBoxColor(spawnchoose_TD[18], 252645375);
TextDrawBackgroundColor(spawnchoose_TD[18], 255);
TextDrawFont(spawnchoose_TD[18], 1);
TextDrawSetProportional(spawnchoose_TD[18], 1);
TextDrawSetShadow(spawnchoose_TD[18], 0);