Accessories_PTD[playerid][0] = CreatePlayerTextDraw(playerid, AccessoriesInfo[playerid][AccessoriesX][0], AccessoriesInfo[playerid][AccessoriesY][0], "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Accessories_PTD[playerid][0], 27.0000, 38.0000);
PlayerTextDrawAlignment(playerid, Accessories_PTD[playerid][0], 1);
PlayerTextDrawColor(playerid, Accessories_PTD[playerid][0], 336860415);
PlayerTextDrawBackgroundColor(playerid, Accessories_PTD[playerid][0], 255);
PlayerTextDrawFont(playerid, Accessories_PTD[playerid][0], 4);
PlayerTextDrawSetProportional(playerid, Accessories_PTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, Accessories_PTD[playerid][0], 0);

Accessories_PTD[playerid][1] = CreatePlayerTextDraw(playerid, AccessoriesInfo[playerid][AccessoriesX][1], AccessoriesInfo[playerid][AccessoriesY][1], "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Accessories_PTD[playerid][1], 26.0000, 8.0000);
PlayerTextDrawAlignment(playerid, Accessories_PTD[playerid][1], 1);
PlayerTextDrawColor(playerid, Accessories_PTD[playerid][1], 623191551);
PlayerTextDrawBackgroundColor(playerid, Accessories_PTD[playerid][1], 255);
PlayerTextDrawFont(playerid, Accessories_PTD[playerid][1], 4);
PlayerTextDrawSetProportional(playerid, Accessories_PTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, Accessories_PTD[playerid][1], 0);
PlayerTextDrawSetSelectable(playerid, Accessories_PTD[playerid][1], true);

Accessories_PTD[playerid][2] = CreatePlayerTextDraw(playerid, AccessoriesInfo[playerid][AccessoriesX][2], AccessoriesInfo[playerid][AccessoriesY][2], "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Accessories_PTD[playerid][2], 26.0000, 8.0000);
PlayerTextDrawAlignment(playerid, Accessories_PTD[playerid][2], 1);
PlayerTextDrawColor(playerid, Accessories_PTD[playerid][2], 623191551);
PlayerTextDrawBackgroundColor(playerid, Accessories_PTD[playerid][2], 255);
PlayerTextDrawFont(playerid, Accessories_PTD[playerid][2], 4);
PlayerTextDrawSetProportional(playerid, Accessories_PTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, Accessories_PTD[playerid][2], 0);
PlayerTextDrawSetSelectable(playerid, Accessories_PTD[playerid][2], true);

Accessories_PTD[playerid][3] = CreatePlayerTextDraw(playerid, AccessoriesInfo[playerid][AccessoriesX][3], AccessoriesInfo[playerid][AccessoriesY][3], "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Accessories_PTD[playerid][3], 26.0000, 8.0000);
PlayerTextDrawAlignment(playerid, Accessories_PTD[playerid][3], 1);
PlayerTextDrawColor(playerid, Accessories_PTD[playerid][3], 623191551);
PlayerTextDrawBackgroundColor(playerid, Accessories_PTD[playerid][3], 255);
PlayerTextDrawFont(playerid, Accessories_PTD[playerid][3], 4);
PlayerTextDrawSetProportional(playerid, Accessories_PTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, Accessories_PTD[playerid][3], 0);
PlayerTextDrawSetSelectable(playerid, Accessories_PTD[playerid][3], true);

Accessories_PTD[playerid][4] = CreatePlayerTextDraw(playerid, AccessoriesInfo[playerid][AccessoriesX][4], AccessoriesInfo[playerid][AccessoriesY][4], "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, Accessories_PTD[playerid][4], 26.0000, 8.0000);
PlayerTextDrawAlignment(playerid, Accessories_PTD[playerid][4], 1);
PlayerTextDrawColor(playerid, Accessories_PTD[playerid][4], -11579393);
PlayerTextDrawBackgroundColor(playerid, Accessories_PTD[playerid][4], 255);
PlayerTextDrawFont(playerid, Accessories_PTD[playerid][4], 4);
PlayerTextDrawSetProportional(playerid, Accessories_PTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, Accessories_PTD[playerid][4], 0);
PlayerTextDrawSetSelectable(playerid, Accessories_PTD[playerid][4], true);

Accessories_PTD[playerid][5] = CreatePlayerTextDraw(playerid, AccessoriesInfo[playerid][AccessoriesX][5], AccessoriesInfo[playerid][AccessoriesY][5], "put"); // ?????
PlayerTextDrawLetterSize(playerid, Accessories_PTD[playerid][5], 0.1423, 0.8241);
PlayerTextDrawAlignment(playerid, Accessories_PTD[playerid][5], 1);
PlayerTextDrawColor(playerid, Accessories_PTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, Accessories_PTD[playerid][5], 255);
PlayerTextDrawFont(playerid, Accessories_PTD[playerid][5], 2);
PlayerTextDrawSetProportional(playerid, Accessories_PTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, Accessories_PTD[playerid][5], 0);

Accessories_PTD[playerid][6] = CreatePlayerTextDraw(playerid, AccessoriesInfo[playerid][AccessoriesX][6], AccessoriesInfo[playerid][AccessoriesY][6], "DROP"); // ?????
PlayerTextDrawLetterSize(playerid, Accessories_PTD[playerid][6], 0.1423, 0.8241);
PlayerTextDrawAlignment(playerid, Accessories_PTD[playerid][6], 1);
PlayerTextDrawColor(playerid, Accessories_PTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, Accessories_PTD[playerid][6], 255);
PlayerTextDrawFont(playerid, Accessories_PTD[playerid][6], 2);
PlayerTextDrawSetProportional(playerid, Accessories_PTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, Accessories_PTD[playerid][6], 0);

Accessories_PTD[playerid][7] = CreatePlayerTextDraw(playerid, AccessoriesInfo[playerid][AccessoriesX][7], AccessoriesInfo[playerid][AccessoriesY][7], "Delete"); // ?????
PlayerTextDrawLetterSize(playerid, Accessories_PTD[playerid][7], 0.1423, 0.8241);
PlayerTextDrawAlignment(playerid, Accessories_PTD[playerid][7], 1);
PlayerTextDrawColor(playerid, Accessories_PTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, Accessories_PTD[playerid][7], 255);
PlayerTextDrawFont(playerid, Accessories_PTD[playerid][7], 2);
PlayerTextDrawSetProportional(playerid, Accessories_PTD[playerid][7], 1);
PlayerTextDrawSetShadow(playerid, Accessories_PTD[playerid][7], 0);

Accessories_PTD[playerid][8] = CreatePlayerTextDraw(playerid, AccessoriesInfo[playerid][AccessoriesX][8], AccessoriesInfo[playerid][AccessoriesY][8], "Close"); // ?????
PlayerTextDrawLetterSize(playerid, Accessories_PTD[playerid][8], 0.1423, 0.8241);
PlayerTextDrawAlignment(playerid, Accessories_PTD[playerid][8], 1);
PlayerTextDrawColor(playerid, Accessories_PTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, Accessories_PTD[playerid][8], 255);
PlayerTextDrawFont(playerid, Accessories_PTD[playerid][8], 2);
PlayerTextDrawSetProportional(playerid, Accessories_PTD[playerid][8], 1);
PlayerTextDrawSetShadow(playerid, Accessories_PTD[playerid][8], 0);

for(new s; s != 9; s++) PlayerTextDrawShow(playerid, Accessories_PTD[playerid][s]);