dm_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 584.1000, 367.3088, "10"); // пусто
PlayerTextDrawLetterSize(playerid, dm_PTD[playerid][0], 0.2128, 1.0872);
PlayerTextDrawAlignment(playerid, dm_PTD[playerid][0], 2);
PlayerTextDrawColor(playerid, dm_PTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, dm_PTD[playerid][0], 255);
PlayerTextDrawFont(playerid, dm_PTD[playerid][0], 3);
PlayerTextDrawSetProportional(playerid, dm_PTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, dm_PTD[playerid][0], 0);

dm_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 584.1000, 384.7265, "5"); // пусто
PlayerTextDrawLetterSize(playerid, dm_PTD[playerid][1], 0.2128, 1.0872);
PlayerTextDrawAlignment(playerid, dm_PTD[playerid][1], 2);
PlayerTextDrawColor(playerid, dm_PTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, dm_PTD[playerid][1], 255);
PlayerTextDrawFont(playerid, dm_PTD[playerid][1], 3);
PlayerTextDrawSetProportional(playerid, dm_PTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, dm_PTD[playerid][1], 0);