press_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 279.7999, 296.8666, "LD_SPAC:white"); // пусто
PlayerTextDrawTextSize(playerid, press_PTD[playerid][0], 84.0000, 42.0000);
PlayerTextDrawAlignment(playerid, press_PTD[playerid][0], 1);
PlayerTextDrawColor(playerid, press_PTD[playerid][0], 353703423);
PlayerTextDrawBackgroundColor(playerid, press_PTD[playerid][0], 255);
PlayerTextDrawFont(playerid, press_PTD[playerid][0], 4);
PlayerTextDrawSetProportional(playerid, press_PTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, press_PTD[playerid][0], 0);

press_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 279.7999, 296.8666, "LD_SPAC:white"); // пусто
PlayerTextDrawTextSize(playerid, press_PTD[playerid][1], 84.0000, 6.0000);
PlayerTextDrawAlignment(playerid, press_PTD[playerid][1], 1);
PlayerTextDrawColor(playerid, press_PTD[playerid][1], 696302079);
PlayerTextDrawBackgroundColor(playerid, press_PTD[playerid][1], 255);
PlayerTextDrawFont(playerid, press_PTD[playerid][1], 4);
PlayerTextDrawSetProportional(playerid, press_PTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, press_PTD[playerid][1], 0);

press_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 290.1998, 320.6960, "LD_SPAC:white"); // пусто
PlayerTextDrawTextSize(playerid, press_PTD[playerid][2], 64.0000, 14.0000);
PlayerTextDrawAlignment(playerid, press_PTD[playerid][2], 1);
PlayerTextDrawColor(playerid, press_PTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, press_PTD[playerid][2], 255);
PlayerTextDrawFont(playerid, press_PTD[playerid][2], 4);
PlayerTextDrawSetProportional(playerid, press_PTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, press_PTD[playerid][2], 0);

press_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 291.3998, 322.7510, "LD_SPAC:white"); // пусто
PlayerTextDrawTextSize(playerid, press_PTD[playerid][3], 61.0000, 10.0000);
PlayerTextDrawAlignment(playerid, press_PTD[playerid][3], 1);
PlayerTextDrawColor(playerid, press_PTD[playerid][3], 353703423);
PlayerTextDrawBackgroundColor(playerid, press_PTD[playerid][3], 255);
PlayerTextDrawFont(playerid, press_PTD[playerid][3], 4);
PlayerTextDrawSetProportional(playerid, press_PTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, press_PTD[playerid][3], 0);

press_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 321.3999, 321.4111, "I_I_I_I_I_I_I_I_I_I_I_I_I_I"); // пусто
PlayerTextDrawLetterSize(playerid, press_PTD[playerid][4], 0.2375, 1.3511);
PlayerTextDrawAlignment(playerid, press_PTD[playerid][4], 2);
PlayerTextDrawColor(playerid, press_PTD[playerid][4], -1);
PlayerTextDrawBackgroundColor(playerid, press_PTD[playerid][4], 255);
PlayerTextDrawFont(playerid, press_PTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, press_PTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, press_PTD[playerid][4], 0);

press_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 321.9999, 305.4844, "Press_Y"); // пусто
PlayerTextDrawLetterSize(playerid, press_PTD[playerid][5], 0.2532, 1.2814);
PlayerTextDrawAlignment(playerid, press_PTD[playerid][5], 2);
PlayerTextDrawColor(playerid, press_PTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, press_PTD[playerid][5], 255);
PlayerTextDrawFont(playerid, press_PTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, press_PTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, press_PTD[playerid][5], 0);
