MainMenu_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 202.0832, 98.4813, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][0], 92.0000, 99.0000);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][0], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][0], 1090519040);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][0], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][0], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][0], 299);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][0], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 266.4666, 104.3851, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][1], 25.2999, 26.2600);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][1], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][1], 286331391);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][1], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][1], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][1], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][1], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 295.5332, 104.3031, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][2], 25.2999, 26.2600);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][2], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][2], 286331391);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][2], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][2], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][2], 18907);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][2], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 266.6665, 133.8332, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][3], 25.2999, 26.2600);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][3], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][3], 286331391);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][3], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][3], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][3], 19030);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][3], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 295.5332, 133.8515, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][4], 25.2999, 26.2600);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][4], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][4], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][4], 286331391);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][4], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][4], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][4], 19029);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][4], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 266.4833, 163.3072, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][5], 25.2999, 26.2600);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][5], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][5], 286331391);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][5], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][5], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][5], 19028);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][5], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][6] = CreatePlayerTextDraw(playerid, 295.5168, 163.2702, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][6], 25.2999, 26.2600);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][6], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][6], 286331391);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][6], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][6], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][6], 19051);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][6], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][7] = CreatePlayerTextDraw(playerid, 332.7000, 100.9110, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][7], 29.6200, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][7], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][7], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][7], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][7], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][7], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][7], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][8] = CreatePlayerTextDraw(playerid, 363.4833, 100.9110, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][8], 29.4799, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][8], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][8], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][8], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][8], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][8], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][8], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][9] = CreatePlayerTextDraw(playerid, 394.2001, 100.8107, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][9], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][9], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][9], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][9], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][9], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][9], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][9], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][9], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][9], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][10] = CreatePlayerTextDraw(playerid, 424.7167, 100.8107, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][10], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][10], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][10], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][10], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][10], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][10], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][10], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][10], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][11] = CreatePlayerTextDraw(playerid, 455.3500, 100.8107, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][11], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][11], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][11], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][11], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][11], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][11], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][11], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][11], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][11], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][12] = CreatePlayerTextDraw(playerid, 332.8500, 132.7776, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][12], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][12], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][12], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][12], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][12], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][12], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][12], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][12], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][12], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][13] = CreatePlayerTextDraw(playerid, 363.3666, 132.7776, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][13], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][13], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][13], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][13], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][13], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][13], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][13], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][13], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][13], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][14] = CreatePlayerTextDraw(playerid, 394.2000, 132.7776, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][14], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][14], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][14], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][14], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][14], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][14], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][14], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][14], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][14], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][15] = CreatePlayerTextDraw(playerid, 424.8168, 132.7776, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][15], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][15], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][15], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][15], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][15], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][15], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][15], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][15], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][15], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][16] = CreatePlayerTextDraw(playerid, 455.5335, 132.7776, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][16], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][16], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][16], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][16], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][16], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][16], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][16], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][16], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][16], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][17] = CreatePlayerTextDraw(playerid, 332.7001, 164.7256, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][17], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][17], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][17], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][17], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][17], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][17], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][17], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][17], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][17], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][18] = CreatePlayerTextDraw(playerid, 363.5335, 164.7442, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][18], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][18], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][18], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][18], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][18], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][18], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][18], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][18], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][18], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][19] = CreatePlayerTextDraw(playerid, 394.0834, 164.7256, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][19], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][19], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][19], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][19], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][19], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][19], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][19], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][19], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][19], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][20] = CreatePlayerTextDraw(playerid, 424.7164, 164.7256, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][20], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][20], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][20], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][20], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][20], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][20], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][20], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][20], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][20], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][21] = CreatePlayerTextDraw(playerid, 455.4331, 164.7442, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][21], 29.4300, 30.5699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][21], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][21], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][21], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][21], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][21], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][21], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][21], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][21], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][22] = CreatePlayerTextDraw(playerid, 332.8497, 196.7922, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][22], 29.4300, 30.4699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][22], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][22], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][22], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][22], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][22], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][22], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][22], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][22], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][23] = CreatePlayerTextDraw(playerid, 363.3497, 196.7922, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][23], 29.4300, 30.4699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][23], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][23], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][23], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][23], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][23], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][23], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][23], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][23], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][24] = CreatePlayerTextDraw(playerid, 394.0498, 196.8108, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][24], 29.4300, 30.4699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][24], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][24], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][24], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][24], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][24], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][24], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][24], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][24], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][25] = CreatePlayerTextDraw(playerid, 424.7828, 196.7368, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][25], 29.4300, 30.4699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][25], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][25], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][25], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][25], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][25], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][25], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][25], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][25], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][26] = CreatePlayerTextDraw(playerid, 455.3829, 196.7554, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][26], 29.4300, 30.4699);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][26], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][26], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][26], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][26], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][26], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][26], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][26], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][26], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][27] = CreatePlayerTextDraw(playerid, 332.7496, 228.5850, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][27], 29.4300, 30.2299);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][27], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][27], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][27], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][27], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][27], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][27], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][27], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][27], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][28] = CreatePlayerTextDraw(playerid, 363.3995, 228.6035, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][28], 29.4300, 30.2299);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][28], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][28], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][28], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][28], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][28], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][28], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][28], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][28], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][29] = CreatePlayerTextDraw(playerid, 394.0162, 228.6035, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][29], 29.6000, 30.2299);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][29], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][29], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][29], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][29], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][29], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][29], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][29], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][29], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][30] = CreatePlayerTextDraw(playerid, 424.9494, 228.6035, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][30], 29.2199, 30.2299);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][30], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][30], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][30], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][30], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][30], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][30], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][30], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][30], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][31] = CreatePlayerTextDraw(playerid, 455.5827, 228.6035, ""); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][31], 29.2199, 30.2299);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][31], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][31], -1);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][31], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][31], 5);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][31], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][31], 0);
PlayerTextDrawSetPreviewModel(playerid, MainMenu_PTD[playerid][31], 3026);
PlayerTextDrawSetPreviewRot(playerid, MainMenu_PTD[playerid][31], 0.0000, 0.0000, 0.0000, 1.0000);

MainMenu_PTD[playerid][32] = CreatePlayerTextDraw(playerid, 246.4499, 202.5852, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][32], 74.3898, 3.4600);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][32], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][32], -1523963137);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][32], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][32], 4);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][32], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][32], 0);

MainMenu_PTD[playerid][33] = CreatePlayerTextDraw(playerid, 246.6499, 209.5856, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][33], 74.2198, 3.5099);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][33], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][33], 5898239);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][33], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][33], 4);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][33], 0);
PlayerTextDrawSetShadow(playerid, MainMenu_PTD[playerid][33], 0);

MainMenu_PTD[playerid][34] = CreatePlayerTextDraw(playerid, 246.6499, 216.8045, "LD_SPAC:white"); // ?????
PlayerTextDrawTextSize(playerid, MainMenu_PTD[playerid][34], 74.2295, 3.3499);
PlayerTextDrawAlignment(playerid, MainMenu_PTD[playerid][34], 1);
PlayerTextDrawColor(playerid, MainMenu_PTD[playerid][34], -5373697);
PlayerTextDrawBackgroundColor(playerid, MainMenu_PTD[playerid][34], 255);
PlayerTextDrawFont(playerid, MainMenu_PTD[playerid][34], 4);
PlayerTextDrawSetProportional(playerid, MainMenu_PTD[playerid][34], 0);