//Food
FoodPTXT[playerid][1] = CreatePlayerTextDraw(playerid, 356.000000, 293.000000, "100$");
PlayerTextDrawLetterSize(playerid, FoodPTXT[playerid][1], 0.390000, 1.000000);
PlayerTextDrawTextSize(playerid, FoodPTXT[playerid][1], 1280.000000, 1280.000000);
PlayerTextDrawAlignment(playerid, FoodPTXT[playerid][1], 0);
PlayerTextDrawColor(playerid, FoodPTXT[playerid][1], 0xFFFFFFFFFFFFFFFF);
PlayerTextDrawUseBox(playerid, FoodPTXT[playerid][1], 0);
PlayerTextDrawBoxColor(playerid, FoodPTXT[playerid][1], 0xFFFFFFFF80808080);
PlayerTextDrawSetShadow(playerid, FoodPTXT[playerid][1], 2);
PlayerTextDrawSetOutline(playerid, FoodPTXT[playerid][1], 1);
PlayerTextDrawBackgroundColor(playerid, FoodPTXT[playerid][1], 0x000000FF);
PlayerTextDrawFont(playerid, FoodPTXT[playerid][1], 2);
PlayerTextDrawSetProportional(playerid, FoodPTXT[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, FoodPTXT[playerid][1], 0);

FoodPTXT[playerid][0] = CreatePlayerTextDraw(playerid, 260.000000, 293.000000, "free");
PlayerTextDrawLetterSize(playerid, FoodPTXT[playerid][0], 0.390000, 1.000000);
PlayerTextDrawTextSize(playerid, FoodPTXT[playerid][0], 1280.000000, 1280.000000);
PlayerTextDrawAlignment(playerid, FoodPTXT[playerid][0], 0);
PlayerTextDrawColor(playerid, FoodPTXT[playerid][0], 0xFFFFFFFFFFFFFFFF);
PlayerTextDrawUseBox(playerid, FoodPTXT[playerid][0], 0);
PlayerTextDrawBoxColor(playerid, FoodPTXT[playerid][0], 0xFFFFFFFF80808080);
PlayerTextDrawSetShadow(playerid, FoodPTXT[playerid][0], 2);
PlayerTextDrawSetOutline(playerid, FoodPTXT[playerid][0], 1);
PlayerTextDrawBackgroundColor(playerid, FoodPTXT[playerid][0], 0x000000FF);
PlayerTextDrawFont(playerid, FoodPTXT[playerid][0], 2);
PlayerTextDrawSetProportional(playerid, FoodPTXT[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, FoodPTXT[playerid][0], 0);