	Roulette_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 276.8818, 173.1333, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][0], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][0], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][0], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][0], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][0], 1550);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][0], 0.0000, 0.0000, 0.0000, 1.0000);

	Roulette_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 314.7361, 173.0000, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][1], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][1], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][1], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][1], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][1], 1277);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][1], 0.0000, 0.0000, 0.0000, 1.0000);

	Roulette_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 352.7644, 173.0334, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][2], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][2], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][2], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][2], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][2], 1550);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][2], 0.0000, 0.0000, 0.0000, 1.0000);

	Roulette_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 352.6272, 213.0836, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][3], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][3], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][3], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][3], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][3], 120);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][3], 0.0000, 0.0000, 0.0000, 1.0000);

	Roulette_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 352.5957, 253.2339, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][4], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][4], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][4], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][4], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][4], 19941);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][4], 0.0000, 0.0000, 0.0000, 1.0000);

	Roulette_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 352.5274, 293.2507, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][5], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][5], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][5], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][5], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][5], 411);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][5], 0.0000, 0.0000, 91.0000, 1.0000);
	PlayerTextDrawSetPreviewVehCol(playerid, Roulette_PTD[playerid][5], 1, 1);

	Roulette_PTD[playerid][6] = CreatePlayerTextDraw(playerid, 314.6140, 293.0841, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][6], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][6], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][6], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][6], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][6], 1550);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][6], 0.0000, 0.0000, 0.0000, 1.0000);

	Roulette_PTD[playerid][7] = CreatePlayerTextDraw(playerid, 276.6116, 293.2674, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][7], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][7], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][7], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][7], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][7], 522);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][7], 0.0000, 0.0000, 100.0000, 1.0000);
	PlayerTextDrawSetPreviewVehCol(playerid, Roulette_PTD[playerid][7], 1, 1);

	Roulette_PTD[playerid][8] = CreatePlayerTextDraw(playerid, 276.5430, 252.8838, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][8], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][8], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][8], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][8], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][8], 1277);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][8], 0.0000, 0.0000, 0.0000, 1.0000);

	Roulette_PTD[playerid][9] = CreatePlayerTextDraw(playerid, 276.6059, 212.9338, ""); // ?????
	PlayerTextDrawTextSize(playerid, Roulette_PTD[playerid][9], 37.0000, 39.0000);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][9], 0x78ED98AA);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][9], 5);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][9], 0);
	PlayerTextDrawSetPreviewModel(playerid, Roulette_PTD[playerid][9], 19941);
	PlayerTextDrawSetPreviewRot(playerid, Roulette_PTD[playerid][9], 0.0000, 0.0000, 0.0000, 1.0000);

	Roulette_PTD[playerid][10] = CreatePlayerTextDraw(playerid, 344.5541, 246.6665, "100"); // ?????
	PlayerTextDrawLetterSize(playerid, Roulette_PTD[playerid][10], 0.2302, 0.8648);
	PlayerTextDrawAlignment(playerid, Roulette_PTD[playerid][10], 2);
	PlayerTextDrawColor(playerid, Roulette_PTD[playerid][10], 0xFFFFFFAA);
	PlayerTextDrawBackgroundColor(playerid, Roulette_PTD[playerid][10], 255);
	PlayerTextDrawFont(playerid, Roulette_PTD[playerid][10], 3);
	PlayerTextDrawSetProportional(playerid, Roulette_PTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, Roulette_PTD[playerid][10], 0);
