Satiety_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 59.9997, 249.9920, "LD_SPAC:white"); // ionoi
PlayerTextDrawTextSize(playerid, Satiety_PTD[playerid][0], 0.0000, 5.0000);
PlayerTextDrawAlignment(playerid, Satiety_PTD[playerid][0], 1);
PlayerTextDrawColor(playerid, Satiety_PTD[playerid][0], 1112566783);
PlayerTextDrawBackgroundColor(playerid, Satiety_PTD[playerid][0], 255);
PlayerTextDrawFont(playerid, Satiety_PTD[playerid][0], 4);
PlayerTextDrawSetProportional(playerid, Satiety_PTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, Satiety_PTD[playerid][0], 0);

Satiety_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 77.3331, 249.9920, "LD_SPAC:white"); // ionoi
PlayerTextDrawTextSize(playerid, Satiety_PTD[playerid][1], 1.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Satiety_PTD[playerid][1], 1);
PlayerTextDrawColor(playerid, Satiety_PTD[playerid][1], 606348408);
PlayerTextDrawBackgroundColor(playerid, Satiety_PTD[playerid][1], 255);
PlayerTextDrawFont(playerid, Satiety_PTD[playerid][1], 4);
PlayerTextDrawSetProportional(playerid, Satiety_PTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, Satiety_PTD[playerid][1], 0);

Satiety_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 97.9996, 249.5773, "LD_SPAC:white"); // ionoi
PlayerTextDrawTextSize(playerid, Satiety_PTD[playerid][2], 1.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Satiety_PTD[playerid][2], 1);
PlayerTextDrawColor(playerid, Satiety_PTD[playerid][2], 606348408);
PlayerTextDrawBackgroundColor(playerid, Satiety_PTD[playerid][2], 255);
PlayerTextDrawFont(playerid, Satiety_PTD[playerid][2], 4);
PlayerTextDrawSetProportional(playerid, Satiety_PTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, Satiety_PTD[playerid][2], 0);

Satiety_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 117.9996, 249.5773, "LD_SPAC:white"); // ionoi
PlayerTextDrawTextSize(playerid, Satiety_PTD[playerid][3], 1.0000, 6.0000);
PlayerTextDrawAlignment(playerid, Satiety_PTD[playerid][3], 1);
PlayerTextDrawColor(playerid, Satiety_PTD[playerid][3], 606348408);
PlayerTextDrawBackgroundColor(playerid, Satiety_PTD[playerid][3], 255);
PlayerTextDrawFont(playerid, Satiety_PTD[playerid][3], 4);
PlayerTextDrawSetProportional(playerid, Satiety_PTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, Satiety_PTD[playerid][3], 0);

Satiety_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 59.9999, 234.3851, "100%"); // ionoi
PlayerTextDrawLetterSize(playerid, Satiety_PTD[playerid][4], 0.1419, 0.6915);
PlayerTextDrawAlignment(playerid, Satiety_PTD[playerid][4], 1);
PlayerTextDrawColor(playerid, Satiety_PTD[playerid][4], -2139062017);
PlayerTextDrawBackgroundColor(playerid, Satiety_PTD[playerid][4], 255);
PlayerTextDrawFont(playerid, Satiety_PTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, Satiety_PTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, Satiety_PTD[playerid][4], 0);

Satiety_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 129.3332, 241.0222, "10_sek"); // ionoi
PlayerTextDrawLetterSize(playerid, Satiety_PTD[playerid][5], 0.1419, 0.6915);
PlayerTextDrawAlignment(playerid, Satiety_PTD[playerid][5], 2);
PlayerTextDrawColor(playerid, Satiety_PTD[playerid][5], 1111638783);
PlayerTextDrawBackgroundColor(playerid, Satiety_PTD[playerid][5], 255);
PlayerTextDrawFont(playerid, Satiety_PTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, Satiety_PTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, Satiety_PTD[playerid][5], 0);