	shop_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 288.4258, 142.1666, "LD_SPAC:white"); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][0], 114.0000, 198.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][0], 252645375);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][0], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][0], 4);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][0], 0);

	shop_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 288.4258, 157.9165, "LD_SPAC:white"); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][1], 114.0000, 3.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][1], 8438015);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][1], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][1], 4);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][1], 0);

	shop_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 362.3838, 142.1666, "LD_SPAC:white"); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][2], 40.0000, 18.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][2], 8438015);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][2], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][2], 4);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][2], 0);

	shop_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 383.2357, 145.0833, "SHOP"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][3], 0.1721, 1.2907);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][3], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][3], 2);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][3], 0);

	shop_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 291.8739, 144.4999, "Jax_Teller"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][4], 0.1862, 1.1565);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][4], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][4], 0);

	shop_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 292.6426, 169.5833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][5], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][5], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][5], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][5], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][5], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][5], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][5], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][6] = CreatePlayerTextDraw(playerid, 328.2503, 169.5833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][6], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][6], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][6], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][6], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][6], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][6], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][6], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][7] = CreatePlayerTextDraw(playerid, 363.8578, 169.5833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][7], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][7], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][7], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][7], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][7], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][7], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][7], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][8] = CreatePlayerTextDraw(playerid, 292.6426, 208.0833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][8], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][8], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][8], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][8], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][8], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][8], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][8], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][9] = CreatePlayerTextDraw(playerid, 328.2502, 208.0833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][9], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][9], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][9], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][9], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][9], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][9], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][9], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][10] = CreatePlayerTextDraw(playerid, 363.8578, 208.0833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][10], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][10], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][10], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][10], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][10], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][10], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][10], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][10], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][11] = CreatePlayerTextDraw(playerid, 292.6424, 246.5833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][11], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][11], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][11], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][11], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][11], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][11], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][11], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][11], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][12] = CreatePlayerTextDraw(playerid, 328.2502, 246.5832, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][12], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][12], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][12], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][12], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][12], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][12], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][12], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][12], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][12], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][13] = CreatePlayerTextDraw(playerid, 363.8579, 246.5832, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][13], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][13], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][13], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][13], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][13], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][13], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][13], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][13], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][14] = CreatePlayerTextDraw(playerid, 292.6427, 285.0833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][14], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][14], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][14], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][14], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][14], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][14], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][14], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][14], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][14], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][15] = CreatePlayerTextDraw(playerid, 328.2504, 285.0833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][15], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][15], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][15], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][15], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][15], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][15], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][15], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][15], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][15], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][15], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][16] = CreatePlayerTextDraw(playerid, 363.8581, 285.0833, ""); // пусто
	PlayerTextDrawTextSize(playerid, shop_PTD[playerid][16], 34.0000, 36.0000);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][16], 1);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][16], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][16], 791621631);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][16], 5);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][16], 0);
	PlayerTextDrawSetSelectable(playerid, shop_PTD[playerid][16], true);
	PlayerTextDrawSetPreviewModel(playerid, shop_PTD[playerid][16], 19382);
	PlayerTextDrawSetPreviewRot(playerid, shop_PTD[playerid][16], 0.0000, 0.0000, 0.0000, 1.0000);

	shop_PTD[playerid][17] = CreatePlayerTextDraw(playerid, 325.6076, 195.8333, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][17], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][17], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][17], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][17], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][17], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][17], 0);

	shop_PTD[playerid][18] = CreatePlayerTextDraw(playerid, 361.2152, 196.4166, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][18], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][18], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][18], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][18], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][18], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][18], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][18], 0);

	shop_PTD[playerid][19] = CreatePlayerTextDraw(playerid, 396.8229, 196.4166, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][19], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][19], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][19], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][19], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][19], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][19], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][19], 0);

	shop_PTD[playerid][20] = CreatePlayerTextDraw(playerid, 325.6077, 234.9165, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][20], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][20], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][20], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][20], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][20], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][20], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][20], 0);

	shop_PTD[playerid][21] = CreatePlayerTextDraw(playerid, 361.2153, 235.4999, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][21], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][21], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][21], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][21], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][21], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][21], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][21], 0);

	shop_PTD[playerid][22] = CreatePlayerTextDraw(playerid, 396.8229, 235.4999, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][22], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][22], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][22], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][22], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][22], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][22], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][22], 0);

	shop_PTD[playerid][23] = CreatePlayerTextDraw(playerid, 325.6076, 273.4166, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][23], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][23], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][23], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][23], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][23], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][23], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][23], 0);

	shop_PTD[playerid][24] = CreatePlayerTextDraw(playerid, 361.2154, 273.9999, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][24], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][24], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][24], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][24], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][24], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][24], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][24], 0);

	shop_PTD[playerid][25] = CreatePlayerTextDraw(playerid, 396.8230, 273.9999, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][25], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][25], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][25], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][25], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][25], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][25], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][25], 0);

	shop_PTD[playerid][26] = CreatePlayerTextDraw(playerid, 325.6077, 311.9166, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][26], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][26], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][26], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][26], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][26], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][26], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][26], 0);

	shop_PTD[playerid][27] = CreatePlayerTextDraw(playerid, 361.6838, 311.9166, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][27], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][27], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][27], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][27], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][27], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][27], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][27], 0);

	shop_PTD[playerid][28] = CreatePlayerTextDraw(playerid, 396.8232, 311.3333, "10000$"); // пусто
	PlayerTextDrawLetterSize(playerid, shop_PTD[playerid][28], 0.1929, 0.9699);
	PlayerTextDrawAlignment(playerid, shop_PTD[playerid][28], 3);
	PlayerTextDrawColor(playerid, shop_PTD[playerid][28], -1);
	PlayerTextDrawBackgroundColor(playerid, shop_PTD[playerid][28], 255);
	PlayerTextDrawFont(playerid, shop_PTD[playerid][28], 1);
	PlayerTextDrawSetProportional(playerid, shop_PTD[playerid][28], 1);
	PlayerTextDrawSetShadow(playerid, shop_PTD[playerid][28], 0);