	Pick_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 290.9998, 328.2267, "LD_SPAC:white"); // пусто
	PlayerTextDrawTextSize(playerid, Pick_PTD[playerid][0], 55.0000, 55.0000);
	PlayerTextDrawAlignment(playerid, Pick_PTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, Pick_PTD[playerid][0], 252645375);
	PlayerTextDrawBackgroundColor(playerid, Pick_PTD[playerid][0], 255);
	PlayerTextDrawFont(playerid, Pick_PTD[playerid][0], 4);
	PlayerTextDrawSetProportional(playerid, Pick_PTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, Pick_PTD[playerid][0], 0);

	Pick_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 294.2000, 331.2133, ""); // пусто
	PlayerTextDrawTextSize(playerid, Pick_PTD[playerid][1], 48.0000, 48.0000);
	PlayerTextDrawAlignment(playerid, Pick_PTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, Pick_PTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, Pick_PTD[playerid][1], 252645375);
	PlayerTextDrawFont(playerid, Pick_PTD[playerid][1], 5);
	PlayerTextDrawSetProportional(playerid, Pick_PTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, Pick_PTD[playerid][1], 0);
	PlayerTextDrawSetPreviewModel(playerid, Pick_PTD[playerid][1], 0);
	PlayerTextDrawSetPreviewRot(playerid, Pick_PTD[playerid][1], 0.0000, 0.0000, 0.0000, 1.0000);

	Pick_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 318.7999, 315.4400, "ITEM"); // пусто
	PlayerTextDrawLetterSize(playerid, Pick_PTD[playerid][2], 0.1795, 1.0872);
	PlayerTextDrawTextSize(playerid, Pick_PTD[playerid][2], 0.0000, 52.0000);
	PlayerTextDrawAlignment(playerid, Pick_PTD[playerid][2], 2);
	PlayerTextDrawColor(playerid, Pick_PTD[playerid][2], -1);
	PlayerTextDrawUseBox(playerid, Pick_PTD[playerid][2], 1);
	PlayerTextDrawBoxColor(playerid, Pick_PTD[playerid][2], 252645375);
	PlayerTextDrawBackgroundColor(playerid, Pick_PTD[playerid][2], 255);
	PlayerTextDrawFont(playerid, Pick_PTD[playerid][2], 2);
	PlayerTextDrawSetProportional(playerid, Pick_PTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, Pick_PTD[playerid][2], 0);

	Pick_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 318.7999, 386.1245, "press:_alt"); // пусто
	PlayerTextDrawLetterSize(playerid, Pick_PTD[playerid][3], 0.1795, 1.0872);
	PlayerTextDrawTextSize(playerid, Pick_PTD[playerid][3], 0.0000, 52.0000);
	PlayerTextDrawAlignment(playerid, Pick_PTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, Pick_PTD[playerid][3], -1);
	PlayerTextDrawUseBox(playerid, Pick_PTD[playerid][3], 1);
	PlayerTextDrawBoxColor(playerid, Pick_PTD[playerid][3], 252645375);
	PlayerTextDrawBackgroundColor(playerid, Pick_PTD[playerid][3], 255);
	PlayerTextDrawFont(playerid, Pick_PTD[playerid][3], 2);
	PlayerTextDrawSetProportional(playerid, Pick_PTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, Pick_PTD[playerid][3], 0);